In [1]:
import os

In [2]:
os.getcwd()

'/home/thienhb/Workspace/med-doc-retrieval/notebooks'

In [3]:
os.chdir("../")

In [4]:
os.getcwd()

'/home/thienhb/Workspace/med-doc-retrieval'

In [5]:
os.listdir('.')

['.env',
 '.python-version',
 'outputs',
 '.pytest_cache',
 'notebooks',
 '.gitignore',
 'pyproject.toml',
 '.ruff_cache',
 'README.md',
 '.git',
 'src',
 'scripts',
 'data',
 '.env.example',
 'configs',
 '.venv',
 'tests',
 'main.py',
 'competition_guide.md',
 'uv.lock',
 'TEAM_GUIDE.md']

In [109]:
import pandas as pd

# Read a single Parquet file into a DataFrame
df = pd.read_parquet("data/processed/parquet_corpus/corpus_part_000.parquet")
df1 = pd.read_parquet("data/processed/parquet_corpus/corpus_part_001.parquet")
df2 = pd.read_parquet("data/processed/parquet_corpus/corpus_part_002.parquet")
df3 = pd.read_parquet("data/processed/parquet_corpus/corpus_part_003.parquet")
df4 = pd.read_parquet("data/processed/parquet_corpus/corpus_part_004.parquet")
df5 = pd.read_parquet("data/processed/parquet_corpus/corpus_part_005.parquet")
corpus = pd.read_parquet("data/raw/vibio_mir/links_corpus.parquet")

# Show the first few rows
print(df.head())

    doc_id                                                url  \
0   733125  https://www.vinmec.com/vie/bai-viet/-u-malt-da...
1  2989609  https://www.a-hospital.com/w/%CE%91%E5%9C%B0%E...
2   323036  https://suckhoecongdongonline.vn/0h-hom-nay-26...
3  2474097           https://baidianfeng.familydoctor.com.cn/
4  3984397      https://www.youlai.cn/yyk/article/136046.html

                                               title  \
0  U malt dạ dày Phần 1: Tổng quan, chẩn đoán và ...
1                                              地中海贫血
2  0h hôm nay 26/7 công bố điểm thi THPT Quốc gia...
3                                         鐨偆绉戦閬撀风櫧鐧滈
4                                   免疫性血小板减少性紫癜-有来医生

                                                text lang  \
0  Bài viết bởi Bác sĩ Mai Viễn Phương - Khoa Khá...   vi
1  地中海贫血\n| A+医学百科 >> 地中海贫血 | \n地中海贫血又称海洋性贫血。是一组遗...   zh
2  Tra cứu điểm thi THPT Quốc gia 2021\nSau 0h hô...   vi
3  鐧界櫆椋庝笉鑳藉悆鍚淮c鐨勯鐗╋紵\n鐧界櫆椋庢槸涓�绉嶈壊绱犵己澶辩殑鐤剧梾锛屼富瑕佹槸鍥...   zh
4  -视频-文章-语音\n免疫性血小板减少性紫癜\n2023-08-03 05:16:17阅读：...   zh

                            domain  char_count   status
0                   www.vinmec.com        7110  success
1               www.a-hospital.com        7894  success
2         suckhoecongdongonline.vn        3147  success
3  baidianfeng.familydoctor.com.cn        3183  success
4                    www.youlai.cn         825  success

In [110]:
corpus.head()

    id                                                url
0  583    http://special.vietnamplus.vn/benh_vien_nhan_ai
1  584  https://bachmai.gov.vn/bai-viet/-nguoi-dan-se-...
2  585  https://bachmai.gov.vn/bai-viet/-roi-loan-su-t...
3  586  https://bachmai.gov.vn/bai-viet/1-4-nguoi-truo...
4  587  https://bachmai.gov.vn/bai-viet/1-5-phai-manh-...

In [7]:
df.iloc[0]

doc_id                                                   733125
url           https://www.vinmec.com/vie/bai-viet/-u-malt-da...
title         U malt dạ dày Phần 1: Tổng quan, chẩn đoán và ...
text          Bài viết bởi Bác sĩ Mai Viễn Phương - Khoa Khá...
lang                                                         vi
domain                                           www.vinmec.com
char_count                                                 7110
status                                                  success
Name: 0, dtype: object

In [8]:
import re
import unicodedata

def clean_medical_text(raw_text: str) -> str:
    # 1. Chuẩn hóa Unicode tiếng Việt về dạng NFC
    text = unicodedata.normalize('NFC', raw_text)
    
    # 2. Xóa phần giới thiệu tác giả/bệnh viện ở đầu bài
    # Ví dụ: "Bài viết bởi Bác sĩ... - Bệnh viện..."
    text = re.sub(r"^Bài viết bởi.*?(?=\n\n|\n[A-Z0-9])", "", text, flags=re.IGNORECASE | re.DOTALL)
    
    # 3. Xóa các câu điều hướng, lời mời xem tiếp ở cuối
    # Ví dụ: "Mời quý khách xem tiếp:...", "Mời quý vị xem tiếp:..."
    text = re.sub(r"Mời quý (khách|vị) xem tiếp:.*", "", text, flags=re.IGNORECASE)
    
    # 4. Xóa phần danh sách tài liệu tham khảo (References)
    # Thường bắt đầu bằng "Nguồn tham khảo :" hoặc các tên tác giả định dạng dạng "- Tên tác giả. Năm."
    text = re.sub(r"Nguồn tham khảo\s*:.*", "", text, flags=re.IGNORECASE | re.DOTALL)
    
    # 5. Xóa các dòng rác hoặc kêu gọi đặt lịch ở chân trang (nếu có)
    text = re.sub(r"Để đặt lịch khám tại viện.*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"Tải và đặt lịch khám tự động.*", "", text, flags=re.IGNORECASE)

    # 6. Chuẩn hóa khoảng trắng và ngắt dòng thừa
    # Thay thế các khoảng trắng liên tiếp bằng 1 khoảng trắng
    text = re.sub(r"[ \t]+", " ", text)
    # Loại bỏ các dòng trống thừa (nhiều hơn 2 lần xuống dòng liên tiếp)
    text = re.sub(r"\n\s*\n", "\n\n", text)
    
    return text.strip()

In [17]:
df.iloc[3]["url"]

'https://baidianfeng.familydoctor.com.cn/'

In [10]:
df.iloc[0]["title"]

'U malt dạ dày Phần 1: Tổng quan, chẩn đoán và triệu chứng'

In [11]:
df.iloc[0]["text"]

'Bài viết bởi Bác sĩ Mai Viễn Phương - Khoa Khám bệnh & Nội khoa - Bệnh viện Đa khoa Quốc tế Vinmec Central Park\nBệnh lý u lympho xảy ra ở nhiều cơ quan trong cơ thể, nhưng có một bệnh lý u lympho liên quan đến niêm mạc dạ dày do Helicobacter Pylori, mà ít được lưu tâm, vấn đề đó sẽ được trình bày trong bài này.\n1. Định vị dạ dày trong cơ thể người\nDạ dày là phần đầu tiên của hệ tiêu hóa nằm bên trong ổ bụng.\nDạ dày hay bao tử là nơi phình to nhất của hệ thống đường tiêu hóa trong cơ thể con người, có cấu tạo phức tạp, thực hiện hai chức năng chính là nghiền cơ học thức ăn, thấm dịch vị và phân hủy thức ăn nhờ hệ enzyme tiêu hóa trong dịch vị. Mặc dù là một phần của cơ thể thế nhưng không phải ai cũng biết dạ dày là gì? Dạ dày là một phần quan trọng trong hệ tiêu hóa của con người, là bộ phận nằm giữa thực quản và tá tràng, phần đầu của ruột non. Đây được xem là bộ phận tiêu hóa lớn nhất có chức năng chứa và tiêu hóa thực phẩm.\n2. Hạch bạch huyết (hạch lympho) là gì?\nHạch bạch huyết (hạch lympho) là một phần của hệ bạch huyết, nằm trong vô số các cấu trúc trơn, hình bầu dục dẹp, rải rác dọc theo các mạch bạch huyết.\nTrong cơ thể con người có khoảng 500-600 hạch nằm chặn trên đường đi của các mạch bạch huyết, thường đứng thành nhóm và nhận bạch huyết của từng vùng cơ thể. Những vị trí phổ biến tập trung nhiều hạch bạch huyết là cổ, nách, bẹn, tuy nhiên thông thường, nó xuất hiện ở khắp cơ thể.\nTrong hệ miễn dịch, hạch bạch huyết có chức năng làm bộ lọc hoặc bẫy giữ lại các phần tử ngoại lai,\nCác hạch có vai trò quan trọng đối với hoạt động của hệ miễn dịch. Hạch bạch huyết có thể bị nóng hoặc sưng lên. Đây là một trong những dấu hiệu cảnh báo một số bệnh lý như viêm họng đến nguy hiểm như ung thư.\n3. Định nghĩa U MALT\nU lymphoma MALT dạ dày là loại u lymphoma non-Hodgkin có đặc tính sao chép và tăng sinh chậm các tế bào B, một loại tế bào miễn dịch trong lớp lót dạ dày. Ung thư này chiếm khoảng 12% trong số ngoài hạch lympho, u lymphoma non-Hodgkin xảy ra trên các nam giới chiếm khoảng 18%, u lymphoma non-Hodgkin ngoài hạch trên các phụ nữ. Trong giai đoạn năm 1999–2003, tỷ lệ mắc MALT lymphoma ở dạ dày hàng năm tại Mỹ khoảng 1/ 100,000 người trong quần thể.\nBình thường, lớp lót dạ dày thiếu mô lympho hay hệ thống miễn dịch bảo vệ, nhưng sự phát triển mô này thường kích thích trong đáp ứng khu trú lớp lót do H. pylori. Chỉ các trường hợp hiếm khiến cho mô này tăng xuất hiện MALT lymphoma. Tuy nhiên, hầu như các bệnh nhân bị MALT lymphoma dạ dày phát triển dấu hiệu nhiễm H. pylori và nguy cơ phát triển khối u này cao hơn gấp 6 lần ở những đối tượng nhiễm hơn đối tượng không nhiễm.\n4. Cơ chế bệnh sinh của U MALT\nU lympho hạch ngoại vi vùng rìa của mô bạch huyết liên quan đến niêm mạc (EMZL-MALT) có liên quan đến kích thích miễn dịch mãn tính do nhiễm trùng hoặc kích thích tự miễn dịch. Mối liên hệ giữa nhiễm khuẩn Helicobacter pylori(HP) và MALT lymphoma dạ dày đã được chứng minh. Việc loại trừ vi khuẩn HP bằng kháng sinh được nổi bật lên là một liệu pháp tiêu chuẩn trong điều trị MALT lymphoma dạ dày giai đoạn sớm HP dương tính. Tỷ lệ đáp ứng cao và tỷ lệ sống lâu dài đã được báo cáo trong các trường hợp bệnh nhân MALT lymphoma dạ dày tại chỗ điều trị với xạ trị liều thấp. Liệu pháp kháng thể đơn dòng và hóa trị được dành riêng cho bệnh nhân thất bại hoặc tái phát sau xạ trị và những người mắc bệnh giai đoạn tiến triển.\nĐây là một phân nhóm tương đối hiếm gặp của u lympho không hodgkin thể tiến triển chậm. Chiếm xấp xỉ 3-7% của tất cả trường hợp u lympho tế bào B. Có nguồn gốc từ các tế bào B nhớ ở vùng rìa của các tổ chức lympho thứ cấp liên kết với niêm mạc của nhiều cơ quan khác nhau, các dòng tế bào B này không chỉ tái phát tại chỗ mà còn có thể chuyển dạng thành tế bào B lớn lan tỏa với nguy cơ lan truyền toàn thân. Dạ dày là cơ quan thường bị ảnh hưởng nhất và HP là nguyên nhân của 90% các trường hợp MALT lymphoma dạ dày. Trong 10% các trường hợp còn lại không phát hiện HP được cho là điều trị không hiệu quả.\n5. Chẩn đoán u MALT\nChẩn đoán HP kết hợp một phương pháp không xâm lấn và phương pháp xâm lấn (ví dụ: hơi thở urê kiểm tra và clotest), để loại trừ khả năng một kết quả âm tính giả ở bệnh nhân teo niêm mạc dạ dày và bệnh nhân dùng thuốc ức chế bơm proton (PPI). Sự tham gia của một type vi khuẩn khác với HP gây ra tình trạng viêm mạn tính dạ dày ở những trường hợp MALT lymphoma HP âm tính nhưng dương tính với H. heilmannii với liệu pháp kháng sinh. Mặc dù đã có báo cáo về các trường hợp MALT lymphoma dạ dày âm tính HP đã được điều trị thành công bằng liệu pháp kháng sinh, một số tác giả cho rằng là do âm tính giả. Xạ trị có hiệu quả đối với bệnh nhân MALT lymphoma dạ dày tại chỗ và được chỉ định cho các trường hợp đáp ứng kém với liệu pháp kháng sinh, HP âm tính. Tỷ lệ sống 5 năm không bệnh là 97% với liều xạ thấp hơn hoặc bằng 30Gy dựa trên thời gian theo dõi trung bình là 7,5 năm. MALT lymphoma xuất hiện ở các tổ chức lympho ngoài hạch, trong đó MALT lymphoma dạ dày (GML - Gastric MALT lymphoma) là phổ biến nhất (70%), ngoài ra còn xuất hiện phổi (14%), tổ chức phụ của nhãn cầu (12%), tuyến giáp (4%) và ruột non (1%).\n6. Lịch sử bệnh U MALT\nHP được phát hiện bởi Marshall và Warren năm 1980 từ niêm mạc dạ dày của bệnh nhân viêm dạ dày mãn tính. Nhiễm HP của dạ dày được coi là nguyên nhân chính của viêm dạ dày mãn tính và là tác nhân chính của MALT lymphoma dạ dày. Kể từ khi Isaacson và Wright báo cáo đầu tiên về MALT vào năm 1983, từ đó đã có nhiều nghiên cứu làm sáng tỏ nhiều khía cạnh của bệnh này.\n7. Triệu chứng lâm sàng u MALT\nTriệu chứng lâm sàng của MALT lymphoma dạ dày thường mờ nhạt không đặc hiệu, có thể có đau bụng vùng thượng vị, nôn dai dẳng, gầy sút cân, xuất huyết tiêu hóa, trong một số ít trường hợp: sốt hoặc đổ mồ hôi đêm có thể xuất hiện (biểu hiện điển hình của hội chứng B)... thậm chí được phát hiện tình cờ mà không có biểu hiện triệu chứng.\nMời quý khách xem tiếp:\nMời quý vị xem tiếp: U malt dạ dày Phần 2: Giải phẫu, Phân loại và cách điều trị\nNguồn tham khảo :\n- Asano N, Iijima K, Koike T, Imatani A, Shimosegawa T. Helicobacter pylori-negative gastric mucosa-associated lymphoid tissue lymphomas: A review. World J Gastroenterol. 2015.\n- Ye H, Liu H, Raderer M, et al. gastric MALT lymphoma Brief report High incidence of t (11 ;18) (q21;q21) in Helicobacter pylori – negative gastric MALT lymphoma. 2013.\n- Koch P, del Valle F, Berdel WE, et al. Primary gastrointestinal non-Hodgkin’s lymphoma: I. Anatomic and histologic distribution, clinical features, and survival data of 371 patients registered in the German Multicenter Study GIT NHL 01/92. J Clin Oncol. 2001;19(18):3861- 3873. doi:10.1200/JCO.2001.19.18.3861\n- Ruskone-Fourmestraux A, Lavergne A, Aegerter PH, et al. Predictive factors for regression of gastric MALT lymphoma after anti-Helicobacter pylori treatment. Gut. 2001;48(3):297-303. doi:10.1136/gut.48.3.297\nĐể đặt lịch khám tại viện, Quý khách vui lòng bấm số HOTLINE, đặt mua GÓI DỊCH VỤ hoặc đặt lịch trực tiếp TẠI ĐÂY. Tải và đặt lịch khám tự động trên ứng dụng My Vinmec để quản lý, theo dõi lịch và đặt hẹn mọi lúc mọi nơi ngay trên ứng dụng.'

In [12]:
clean_medical_text(df.iloc[0]["text"])

'Bệnh lý u lympho xảy ra ở nhiều cơ quan trong cơ thể, nhưng có một bệnh lý u lympho liên quan đến niêm mạc dạ dày do Helicobacter Pylori, mà ít được lưu tâm, vấn đề đó sẽ được trình bày trong bài này.\n1. Định vị dạ dày trong cơ thể người\nDạ dày là phần đầu tiên của hệ tiêu hóa nằm bên trong ổ bụng.\nDạ dày hay bao tử là nơi phình to nhất của hệ thống đường tiêu hóa trong cơ thể con người, có cấu tạo phức tạp, thực hiện hai chức năng chính là nghiền cơ học thức ăn, thấm dịch vị và phân hủy thức ăn nhờ hệ enzyme tiêu hóa trong dịch vị. Mặc dù là một phần của cơ thể thế nhưng không phải ai cũng biết dạ dày là gì? Dạ dày là một phần quan trọng trong hệ tiêu hóa của con người, là bộ phận nằm giữa thực quản và tá tràng, phần đầu của ruột non. Đây được xem là bộ phận tiêu hóa lớn nhất có chức năng chứa và tiêu hóa thực phẩm.\n2. Hạch bạch huyết (hạch lympho) là gì?\nHạch bạch huyết (hạch lympho) là một phần của hệ bạch huyết, nằm trong vô số các cấu trúc trơn, hình bầu dục dẹp, rải rác dọc theo các mạch bạch huyết.\nTrong cơ thể con người có khoảng 500-600 hạch nằm chặn trên đường đi của các mạch bạch huyết, thường đứng thành nhóm và nhận bạch huyết của từng vùng cơ thể. Những vị trí phổ biến tập trung nhiều hạch bạch huyết là cổ, nách, bẹn, tuy nhiên thông thường, nó xuất hiện ở khắp cơ thể.\nTrong hệ miễn dịch, hạch bạch huyết có chức năng làm bộ lọc hoặc bẫy giữ lại các phần tử ngoại lai,\nCác hạch có vai trò quan trọng đối với hoạt động của hệ miễn dịch. Hạch bạch huyết có thể bị nóng hoặc sưng lên. Đây là một trong những dấu hiệu cảnh báo một số bệnh lý như viêm họng đến nguy hiểm như ung thư.\n3. Định nghĩa U MALT\nU lymphoma MALT dạ dày là loại u lymphoma non-Hodgkin có đặc tính sao chép và tăng sinh chậm các tế bào B, một loại tế bào miễn dịch trong lớp lót dạ dày. Ung thư này chiếm khoảng 12% trong số ngoài hạch lympho, u lymphoma non-Hodgkin xảy ra trên các nam giới chiếm khoảng 18%, u lymphoma non-Hodgkin ngoài hạch trên các phụ nữ. Trong giai đoạn năm 1999–2003, tỷ lệ mắc MALT lymphoma ở dạ dày hàng năm tại Mỹ khoảng 1/ 100,000 người trong quần thể.\nBình thường, lớp lót dạ dày thiếu mô lympho hay hệ thống miễn dịch bảo vệ, nhưng sự phát triển mô này thường kích thích trong đáp ứng khu trú lớp lót do H. pylori. Chỉ các trường hợp hiếm khiến cho mô này tăng xuất hiện MALT lymphoma. Tuy nhiên, hầu như các bệnh nhân bị MALT lymphoma dạ dày phát triển dấu hiệu nhiễm H. pylori và nguy cơ phát triển khối u này cao hơn gấp 6 lần ở những đối tượng nhiễm hơn đối tượng không nhiễm.\n4. Cơ chế bệnh sinh của U MALT\nU lympho hạch ngoại vi vùng rìa của mô bạch huyết liên quan đến niêm mạc (EMZL-MALT) có liên quan đến kích thích miễn dịch mãn tính do nhiễm trùng hoặc kích thích tự miễn dịch. Mối liên hệ giữa nhiễm khuẩn Helicobacter pylori(HP) và MALT lymphoma dạ dày đã được chứng minh. Việc loại trừ vi khuẩn HP bằng kháng sinh được nổi bật lên là một liệu pháp tiêu chuẩn trong điều trị MALT lymphoma dạ dày giai đoạn sớm HP dương tính. Tỷ lệ đáp ứng cao và tỷ lệ sống lâu dài đã được báo cáo trong các trường hợp bệnh nhân MALT lymphoma dạ dày tại chỗ điều trị với xạ trị liều thấp. Liệu pháp kháng thể đơn dòng và hóa trị được dành riêng cho bệnh nhân thất bại hoặc tái phát sau xạ trị và những người mắc bệnh giai đoạn tiến triển.\nĐây là một phân nhóm tương đối hiếm gặp của u lympho không hodgkin thể tiến triển chậm. Chiếm xấp xỉ 3-7% của tất cả trường hợp u lympho tế bào B. Có nguồn gốc từ các tế bào B nhớ ở vùng rìa của các tổ chức lympho thứ cấp liên kết với niêm mạc của nhiều cơ quan khác nhau, các dòng tế bào B này không chỉ tái phát tại chỗ mà còn có thể chuyển dạng thành tế bào B lớn lan tỏa với nguy cơ lan truyền toàn thân. Dạ dày là cơ quan thường bị ảnh hưởng nhất và HP là nguyên nhân của 90% các trường hợp MALT lymphoma dạ dày. Trong 10% các trường hợp còn lại không phát hiện HP được cho là điều trị không hiệu quả.\n5. Chẩn đoán u MALT\nChẩn đoán HP kết hợp một phương pháp không xâm lấn và phương pháp xâm lấn (ví dụ: hơi thở urê kiểm tra và clotest), để loại trừ khả năng một kết quả âm tính giả ở bệnh nhân teo niêm mạc dạ dày và bệnh nhân dùng thuốc ức chế bơm proton (PPI). Sự tham gia của một type vi khuẩn khác với HP gây ra tình trạng viêm mạn tính dạ dày ở những trường hợp MALT lymphoma HP âm tính nhưng dương tính với H. heilmannii với liệu pháp kháng sinh. Mặc dù đã có báo cáo về các trường hợp MALT lymphoma dạ dày âm tính HP đã được điều trị thành công bằng liệu pháp kháng sinh, một số tác giả cho rằng là do âm tính giả. Xạ trị có hiệu quả đối với bệnh nhân MALT lymphoma dạ dày tại chỗ và được chỉ định cho các trường hợp đáp ứng kém với liệu pháp kháng sinh, HP âm tính. Tỷ lệ sống 5 năm không bệnh là 97% với liều xạ thấp hơn hoặc bằng 30Gy dựa trên thời gian theo dõi trung bình là 7,5 năm. MALT lymphoma xuất hiện ở các tổ chức lympho ngoài hạch, trong đó MALT lymphoma dạ dày (GML - Gastric MALT lymphoma) là phổ biến nhất (70%), ngoài ra còn xuất hiện phổi (14%), tổ chức phụ của nhãn cầu (12%), tuyến giáp (4%) và ruột non (1%).\n6. Lịch sử bệnh U MALT\nHP được phát hiện bởi Marshall và Warren năm 1980 từ niêm mạc dạ dày của bệnh nhân viêm dạ dày mãn tính. Nhiễm HP của dạ dày được coi là nguyên nhân chính của viêm dạ dày mãn tính và là tác nhân chính của MALT lymphoma dạ dày. Kể từ khi Isaacson và Wright báo cáo đầu tiên về MALT vào năm 1983, từ đó đã có nhiều nghiên cứu làm sáng tỏ nhiều khía cạnh của bệnh này.\n7. Triệu chứng lâm sàng u MALT\nTriệu chứng lâm sàng của MALT lymphoma dạ dày thường mờ nhạt không đặc hiệu, có thể có đau bụng vùng thượng vị, nôn dai dẳng, gầy sút cân, xuất huyết tiêu hóa, trong một số ít trường hợp: sốt hoặc đổ mồ hôi đêm có thể xuất hiện (biểu hiện điển hình của hội chứng B)... thậm chí được phát hiện tình cờ mà không có biểu hiện triệu chứng.'

In [ ]:
vi_docs =

In [24]:
for line in df.iloc[10]["text"].split("\n"):
    print(line)

关键词： 平滑肌组织瘤；平滑肌肉瘤；腔外型；胃
【摘要】目的总结腔外型胃平滑肌肿瘤的诊断及治疗经验。方法回顾性分析过去20年48例腔外型胃平滑肌肿瘤的临床特点、辅助检查的准确率以及手术方式。结果48例腔外型胃平滑肌肿瘤占同期胃平滑肌肿瘤的68.6％，主要临床表现为腹部包块37.9％，消化道出血37.9％及腹部不适33.3％。术前胃肠钡餐及胃镜检查准确率分别为57.9％及41.7％，术前确诊率为49.4％。手术以胃楔形切除及胃大部分切除为主。结论腔外型胃平滑肌肿瘤早期缺乏特异性临床表现，易误诊。胃肠钡餐及胃镜联合B超和CT可提高确诊率。治疗上以胃楔形切除及胃大部分切除为主，不必常规清扫淋巴结。
Exogastric tumors of gastric smooth muscle
HE Yulong, LIU Tongcheng, ZHENG Zhangqing, et al
(Division of Gastrointestinal and Pancreatic Surgery, First Affiliated Hospital, Sun Yat sen University of Medical Scienses,Guangzhou 510080,China)
【Abstract】 Objective To investigate the clinical features, diagnostic methods and treatment principles of exogastric gastric smooth muscle tumor. Method Clinical presentations, diagnostic procedures and surgical treatments of 48 cases with exogastric gastric smooth muscle tumor during past 20 years were analyzed retrospectively.Results Fourty eight cases of exogastric gastric smooth muscle tumors accounted for 68. 6％ of all the patients with gastric smooth muscle tumors. Abdominal mass, gastrointestinal bleeding, and abdominal discomfort were the most common symptoms, occurring in 37. 9％ , 37. 9％ and 33. 3％ patients respectively. The accuracy rates of preoperative diagnosis with upper gastrointestinal barium study and gastric endoscopy were 57. 9％ and 41. 7％ . The overall accuracy rate of preoperative diagnosis was 49. 4％ . The most common types of resection were wedge resection and partial gastrectomy.Conclusions Misdiagnosis rate is high in exogastric tumors because of lack of specific clinical manifestations during the early stage. Upper gastrointestinal barium study and gastric endoscopy, in combination with ultrasonography and CT, can increase the accuracy rate of diagnosis of such disease. The main surgical managements are wedge resection and partial gastrectomy, and routine lymphadenectomy is not necessary.
【Key words】 Smooth muscle tumor； Leiomyosarcoma； Exogastric type; Stomach
胃平滑肌肿瘤临床上比较少见，约占胃全部肿瘤的0.9％～1.3％，胃良性肿瘤的17％～40％[1]。病程初期症状隐匿，诊断比较困难，尤其腔外型胃平滑肌肿瘤早期缺乏特异性表现，易误诊。为了更加深入认识腔外型胃平滑肌肿瘤的临床特点、诊断方法和治疗原则，我们就近20年来收治的48例患者，结合文献总结分析如下。
临床资料
1980年1月至1999年12月共收治70例经手术及病理证实的胃平滑肌肿瘤，其中腔外型48例占68.6％，良性平滑肌肿瘤19例，平滑肌肉瘤29例。本组一般临床资料见表1，辅助检查及其结果见表2。本组从出现症状到确诊平均18.9个月，其中发现腹部包块到手术时间最短20d，最长12个月，平均5.6个月。
讨论
胃平滑肌肿瘤临床上缺乏特异性表现，给诊断带来困难。而腔外型平滑肌肿瘤由于瘤体呈外生性生长，早期往往无特殊表现或仅有腹部轻度不适，待出现明显症状时多数已为肿瘤压迫邻近脏器或穿破胃黏膜引起消化道出血。故确诊时肿瘤一般较大，部分平滑肌肉瘤可与周围组织粘连或侵及邻近脏器。本组病例中以消化道出血来诊者18例（37.5％），腹部包块18例（37.5％），腹部不适16例（33.3％），出现症状到确诊时间平均18.9个月，其中发现腹部包块到手术时间最短20d，最长12个月，平均5.6个月。说明本病的临床表现，目前尚未能引起临床医师的足够重视，往往忽略早期的非特异性表现，以致延误了诊治。
表1 48例腔外型胃平滑肌肿瘤临床资料
　　项目 平滑肌瘤(19例) 平滑肌肉瘤(29例) 总计(48例)
　　性别(男∶女) 6∶13 15∶14 21∶27
　　年龄(平均54.4)(岁) 53.9(27～74) 54.7(5～76) 54.4(5～76)
　　临床表现[例(％)]
　　上消化道出血 9(47.4) 9(31.0) 18(37.5)
　　上腹部肿物 5(26.3) 13(44.8) 18(37.5)
　　上腹部不适 6(31.6) 10(34.5) 16(33.3)
　　病变部位[例(％)]
　　胃底 7(36.8) 13(44.8) 20(41.7)
　　胃体 10(52.6) 15(51.7) 25(52.1)
　　胃窦 2(10.5) 1(3.4) 3(6.3)
　　肿瘤直径[例(％)]
　　＜3cm 7(36.8) 0 7(14.6)
　　3～5cm 5(26.3) 3(10.3) 8(16.7)
　　＞5cm 7(36.8) 26(89.7) 33(68.8)
　　手术方式[例(％)]
　　胃楔形切除 9(47.4) 12(41.4) 21(43.8)
　　近端胃大部切除 9(47.4) 1(3.4) 10(20.8)
　　远端胃大部切除 1(5.3) 6(20.7) 7(14.6)
　　全胃切除 0 3(10.3) 3(6.3)
　　合并脏器切除 0 7(24.1) 7(14.6)
表2 48例胃均滑肌肿瘤辅助检查方法及结果[例(%)]
项目 平滑肌瘤 平滑肌肉瘤 总计
例数 临床准确率 例数 临床准确率 例数 临床准确率
　　胃肠钡餐 8 6(6/8) 11 5(45.5) 19 11(57.9)
　　胃镜 11 4(36.4) 13 6(46.2) 24 10(41.7)
　　B型超声 7 4(4/7) 16 10(62.5) 23 14(60.9)
　　CT 4 4(4/4) 12 8(66.7) 16 12(75.0)
　　腔内超声 1 1(1/1) 　 　 1 1(1/1)
　　动脉造影 　 　 2 2(2/2) 2 2(2/2)
胃镜及钡餐透视是目前胃平滑肌肿瘤的主要检查方法，有报道确诊率分别为43.8％和42.1％[2],腔外型准确率较低，本组胃镜确诊率41.7％，钡餐透视57.9％，原因在于肿瘤外生性生长，由于腹腔间隙大，瘤体未造成对胃壁的挤压，故很难通过钡餐或胃镜确诊。B超及CT对腔外型肿瘤的诊断价值较高，通过B超或CT检查，可观察到胃壁是否增厚，肿瘤部位及大小以及与周围脏器的关系，胃周淋巴结有无肿大等。本组B超确诊率为60.9％，CT为75.0％，故这两项检查仍为诊断本病的重要手段。但由于肿瘤较大，常与肝、胰等脏器有重叠，以致易误诊为肝、胰、腹膜后肿物[3]。
如何提高腔外型平滑肌肿瘤的术前诊断率？我们认为，对不明原因的上腹部不适、消化道出血（呕血或黑便）以及腹部包块，均要考虑到胃平滑肌肿瘤的可能，尤其早期出现的上腹部不适更应警惕本病的存在。若胃镜或胃钡餐检查提示胃腔受压，抑或检查结果阴性但无法解释早期出现的症状时，应结合B超或CT进一步检查，有条件的医院可开展超声内镜。该检查能同时显示胃壁及壁外瘤体全貌以及胃壁各层受侵犯的图象，该技术是目前较为理想的检查方法，但尚不能普及。选择性动脉造影对了解肿瘤的血供有帮助，因其有创伤，故不作为常规检查，但在难以判断肿瘤来源时亦不失为一种有效的辅助检查。本组有2例平滑肌肉瘤由于瘤体大，与肝及盆腔脏器有重叠，CT、B超无法确定其来源，最后通过选择性动脉造影而确诊。
胃平滑肌瘤行楔形切除或胃部分切除术已无争议，但平滑肌肉瘤作何术式、是否清扫淋巴结尚有不同观点。由于胃平滑肌肉瘤淋巴结转移少见，以局部浸润及血行转移为主，多见于肝脏、肺等[4]，亦有转移至甲状腺的个案报道[5]，因此，胃平滑肌肉瘤的手术方式以胃楔形切除已经足够，但切除应距肿瘤边缘3～5cm，此方法尤适用于腔外型。Yoshida等[6]报道28例胃平滑肌肉瘤，初次手术及复发时均未发现有淋巴结转移，腹腔镜行胃楔形切除与常规的系统清扫淋巴结手术相比结果差异无显著性，因此认为手术无须进行淋巴结清扫，楔形切除应是首选。Grant等[7]分析53例胃平滑肌肉瘤患者生存曲线及肿瘤复发方式，认为只有肿瘤大小与分化程度是影响预后因素，附加淋巴结清扫和肿瘤切缘宽的根治性胃切除并不能优于保守性的手术即局部切除。本组平滑肌瘤楔
形切除9例(47.4％)；胃部分切除10例(52.7％)；平滑肌肉瘤楔形切除12例(41.4％)；胃部分切除7例(24.1％)；全胃切除3例。胃部分切除与胃楔形切除比例相近，原因是早期对该病的生物学行为认识不足所致。纵观手术方式的发展，楔形切除已逐渐成为主要手术方式，单纯胃楔形切除患者恢复快，同时没有胃大部分切除术后的各种并发症，术后生存质量明显提高，也易被患者接受。必须强调，对于较大的平滑肌瘤（大于3cm），术中应常规送组织冰冻活检，确定有无恶变以及切除缘有无带瘤，避免切缘阳性，减少早期复发。若肿瘤基底较大，或已侵及邻近脏器，可行全胃切除或合并侵及的脏器切除。
参考文献
1,吴阶平，裘法祖，主编.黄家驷外科学.第5版.北京：人民卫生出版社，1986.11081109.
2,郑进军，张国林，张自顺,等.胃平滑肌肿瘤42例临床分析.中国肿瘤临床与康复,1996,6769.
3,Evans HL. Smooth muscle tumors of gastrointestinal tract:a study of 56 cases followed for a minimum of 10 years.Cancer,1985,56:2242 2250.
4,Shiu MH, Farr GH,Papachristou DN,et al.Myosarcoma of the stomach:natural history,prognosis and management.Cancer,1982,49:177 187.
5,Chen H, Niool TL,Vdelsman R. Clinically significant,isolated metastatic disease to the thyroid gland.World J Surg,1997,23:177 180.
6,Yoshida M,Otani Y, Ohgami M, et al.Surgical management of gastric leiomyosarcoma:eveluation of the propriety of laparoscopic wedge resection.Warld J Surg,1997,21:440 443.
7,Grant CS, Kim CH, Farrugia G, et al.Gastric leiomyosarcoma:prognostic factors and surgical management.Arch Surg,1991,126:985 990.

擅长领域：李永翔，医学博士，教授，主任医师，博士生导师，安徽省学术和技术带头人，安徽省卫计委青年领军人才，普外科行政副主任兼胃肠外科（八病区、腹腔镜外科中心）主任。国家卫计委普外科内镜质控专家，中华医学会安徽省外科学会青年副主任委员，安徽微创医学会副理事长，安徽省抗癌协会微创专业委员会主任委员、胃癌专业委员会常委，中华医学会安徽省外科分会腔镜及内镜学组委员。中国抗癌协会大肠癌专业委员会腹腔镜学组委员、中国医师协会微创专业委员会中青年委员会委员、中国医师协会及世界内镜协会无气腹腹腔镜委员会委员。 1991年毕业于安徽医科大学临床医学系，2006年7月复旦大学毕业获得外科学博士学位，2008年至2009年在德国哥廷根大学Diakonie医院、汉诺威医学院外科学习,多次赴美国、韩国、法国、奥地利、香港进行胃癌及大肠癌手术的学习和交流并在国际会议作大会发言。精通各类胃肠道肿瘤及非肿瘤疾病的手术治疗，对各类疝及脾脏疾病及肝胆胰疾病的外科治疗也颇为擅长，熟练掌握各类普外科手术技术，能够熟练进行胃肠道肿瘤根治、半肝切除、胰头十二指肠切除、联合脏器切除、乳腺及甲状腺癌根治等普外科复杂及常规手术，率先在省内开展完全腹腔镜下腹腔镜贲门癌根治+Orvil消化道重建术、巨脾切除+门奇静脉断流术、腹胸腔镜联合食道癌根治术及经脐单孔腹腔镜结肠癌根治及胆囊切除、腹腔镜食管裂孔疝修补等手术；是省内最早规模开展腹腔镜下结、直肠癌根治、胃癌根治等手术者，安徽省普外科领域率先开展达芬奇机器人手术者，采用腹腔镜治疗消化道肿瘤的数量和疗效处于全省领先国内先进行列，腹腔镜胃癌根治获得安徽省手术视频比赛一等奖并获中部四省（苏皖鲁豫）手术视频比赛第一名，腹腔结直肠癌根治术进入全国手术视频比赛总决赛并获得风范达人奖（全国有8名参加决赛）。达芬奇机器人手术已开展：胃癌根治、结肠癌根治、直肠癌根治、胆总管下段癌行完全腔镜下胰头十二指肠切除术、食管裂孔疝修补，处于国内先进行列（部分处于国内领先）。每年多次在国内外进行讲学。完成国家自然科学基金面上项目1项；主持国家自然科学基金面上项目1项；第一参与人参与国家自然基金项目2项；主持包括安徽省科技厅重点项目：“腹腔镜联合内镜技术在消化道疾病诊治中的应用”等省级科研课题4项；主持厅级及院内项目3项。科研研究方向：胃肠道肿瘤的基础及临床研究、移植免疫，目前正指导多名研究生进行这方面的研究工作，以第一作者或通讯作者发表国内外杂志发表论文60余篇（其中SCI英文论文10篇，其它英文论文2篇，最高影响因子5.4分），担任世界胃肠杂志及中华细胞与干细胞移植杂志编委。获得省级科技进步一等奖1项，2008年获得全国“五一”劳动奖状1项，并被中华全国总工会及国家教育部授予“工人先锋号”,2013年获得中华外科青年学者奖。
擅长领域：各部位胃癌D2标准化根治手术、结肠癌根治、直肠癌根治手术。尤其一直从事炎症性疾病如克罗恩（俗称克隆病）病和溃疡性结肠炎的基础和临床研究，对肠内外营养、各种复杂性肠瘘的处理经验丰富。
擅长领域：子宫肌瘤、肝癌、前列腺增生、骨肿瘤、膀胱癌、前列腺癌、直肠癌、乳腺肿瘤、肾癌、盆腔肿瘤、腹膜后肿瘤、胰腺癌、及恶性肿瘤。

In [13]:
len(df.iloc[0]["text"])

7110

In [97]:
from src.ingestion.chunker import DocumentChunker

In [ ]:
# 2. Khởi tạo Chunker (tự động ngắt theo câu/đoạn tự nhiên, không ngắt cụt từ)                                                                                                                               
chunker = DocumentChunker(                                                                                                                                                                                   
    max_chunk_size=1200,    # Độ dài tối đa mỗi chunk (ký tự)                                                                                                                                                 
    chunk_overlap=200,      # Độ gối đầu giữa 2 chunk liên tiếp (để không mất ngữ cảnh)                                                                                                                       
    split_by_sentences=True # Ưu tiên ngắt tại dấu chấm, hỏi, than
)

In [96]:
# 3. Thực hiện tách chunk                                                                                                                                                                                    
chunks = chunker.chunk_document(doc_id="doc_123", text=df.iloc[31]["text"], lang="vi")
# 4. Xem kết quả
print(f"Tổng số chunks tạo ra: {len(chunks)}\n")
for i, c in enumerate(chunks):
    print(f"🔹 [Chunk {i+1}] ID: {c.chunk_id} | Vị trí: [{c.char_start}:{c.char_end}] | Độ dài: {len(c.chunk_text)} ký tự")
    print(f"\"{c.chunk_text}\"\n")

NameError: name 'chunker' is not defined

In [93]:
def display_chunks(doc_id: int, text: str):
    chunks = chunker.chunk_document(doc_id=str(doc_id), text=text, lang="vi")
    # 4. Xem kết quả
    print(f"Tổng số chunks tạo ra: {len(chunks)}\n")
    for i, c in enumerate(chunks):
        print(f"🔹 [Chunk {i+1}] ID: {c.chunk_id} | Vị trí: [{c.char_start}:{c.char_end}] | Độ dài: {len(c.chunk_text)} ký tự")
        print(f"\"{c.chunk_text}\"\n")

In [46]:
all_df = pd.concat([df, df1, df2, df3, df4, df5], ignore_index=True)

In [47]:
all_df

,doc_id,url,title,text,lang,domain,char_count,status
0,733125,https://www.vinmec.com/vie/bai-viet/-u-malt-da...,"U malt dạ dày Phần 1: Tổng quan, chẩn đoán và ...",Bài viết bởi Bác sĩ Mai Viễn Phương - Khoa Khá...,vi,www.vinmec.com,7110,success
1,2989609,https://www.a-hospital.com/w/%CE%91%E5%9C%B0%E...,地中海贫血,地中海贫血\n| A+医学百科 >> 地中海贫血 | \n地中海贫血又称海洋性贫血。是一组遗...,zh,www.a-hospital.com,7894,success
2,323036,https://suckhoecongdongonline.vn/0h-hom-nay-26...,0h hôm nay 26/7 công bố điểm thi THPT Quốc gia...,Tra cứu điểm thi THPT Quốc gia 2021\nSau 0h hô...,vi,suckhoecongdongonline.vn,3147,success
3,2474097,https://baidianfeng.familydoctor.com.cn/,鐨偆绉戦閬撀风櫧鐧滈,鐧界櫆椋庝笉鑳藉悆鍚淮c鐨勯鐗╋紵\n鐧界櫆椋庢槸涓�绉嶈壊绱犵己澶辩殑鐤剧梾锛屼富瑕佹槸鍥...,zh,baidianfeng.familydoctor.com.cn,3183,success
4,3984397,https://www.youlai.cn/yyk/article/136046.html,免疫性血小板减少性紫癜-有来医生,-视频-文章-语音\n免疫性血小板减少性紫癜\n2023-08-03 05:16:17阅读：...,zh,www.youlai.cn,825,success
...,...,...,...,...,...,...,...,...
447716,3539383,https://www.familydoctor.com.cn/baby/a/201512/...,鍎跨閬楀翱鐥囩殑椋熺枟鏂规硶鏈夊摢浜� 瑗垮尰濡備綍娌荤枟濂�,儿遗尿症的食疗方法有哪亄17 西医如何治疗奄17\n孩子大了老尿床，其实參昁尿症在作祟的，在...,zh,www.familydoctor.com.cn,1505,success
447717,2145335,https://ask.39.net/question/102529847.html,骶尾部藏毛窦手术后怎么大便,发病时间：不清楚\n补充说明：骶尾部藏毛窦手术后怎么大便\n我要咨询\n精选回答(1)\n藏...,zh,ask.39.net,472,success
447718,2998223,https://www.a-hospital.com/w/%E4%B8%B4%E6%B4%A...,临洮县人民医院,临洮县人民医院\n临洮县人民医院信息概要：\n- 医院地址：甘肃省定西地区临洮县新\n- 联...,zh,www.a-hospital.com,3721,success
447719,331646,https://suckhoecongdongonline.vn/bac-si-goc-vi...,Bác sĩ gốc Việt bị kéo lê trên máy bay Mỹ lần ...,Trong cuộc phỏng vấn hôm 9/4 trên chương trình...,vi,suckhoecongdongonline.vn,3846,success
447720,4039127,https://zhongyibaodian.net/a/11107.html,乐卡地平,"乐卡地平\n［化学结构式］\n1,4-双氢-2,6-二甲基-4-(3-硝基苯基)-3,5-吡...",zh,zhongyibaodian.net,2105,success

In [67]:
vi_sentences = []
zh_sentences = []

for index, row in all_df.iterrows():
    text = row["text"]
    splits = text.split("\n")

    if row["lang"] == "vi":
        vi_sentences.append(
            {"text": row["text"], "url": row["url"], "title": row["title"]}
        )
    else:
        zh_sentences.append(
            {"text": row["text"], "url": row["url"], "title": row["title"]}
        )

In [68]:
len(vi_sentences)

227852

In [51]:
vi_sentences[-1]

{'text': 'Trong cuộc phỏng vấn hôm 9/4 trên chương trình Good Morning America, bác sĩ Mỹ gốc Việt David Dao cho hay dù sự việc xảy ra tròn 2 năm trước khiến mình và gia đình rất hoảng loạn, ông không hối tiếc vì đã giữ vững quan điểm và khiến hãng United Airlines phải xem xét lại các chính sách.\nNgày 9/4/2017, ông Dao vừa lên chuyến bay 3411 từ Chicago đi Louisville, bang Kentucky không lâu thì bất ngờ được thông báo rằng mình phải rời đi để nhường ghế cho các nhân viên của United Airlines, do chuyến bay bị đặt vé quá chỗ.\nTheo video do các hành khách khác quay lại, ông Dao bị các nhân viên an ninh dùng vũ lực lôi khỏi ghế ngồi dù đã thắt dây an toàn và bị kéo lê trên mặt đất giữa những tiếng la hét hoảng hốt. Một nhân chứng kể trong lúc bị lôi đi, mặt ông Dao va vào tay vịn ghế máy bay, khiến miệng ông chảy máu.\n10 phút sau đó, ông chạy ngược lại với gương mặt vẫn chảy máu, quần áo xộc xệch, mắt kính suýt rơi ra. Ông luôn miệng nói: "Họ sẽ giết tôi, tôi muốn về nhà". Các nhân viên an ninh tiếp tục xuất hiện và đưa ông ra khỏi máy bay lần thứ hai, nhưng lần này là trên một chiếc cáng. Những đoạn video ghi lại toàn bộ sự việc đã tạo nên làn sóng phẫn nộ trên toàn thế giới.\nÔng Dao cho hay nhiều tháng sau, ông vẫn không dám xem lại cảnh tượng hôm đó. "Tôi chỉ khóc", ông nói.\nDao kể rằng ông đã kiên quyết không rời khỏi máy bay vì cảm thấy đang bị phân biệt đối xử và ông cần phải quay về Kentucky để dự lễ khánh thành một phòng khám mà ông thành lập cho các cựu binh Mỹ. Sau khi bị lôi khỏi ghế, ông cho hay mình không nhớ được gì vì đầu bị va vào trần cabin. Ông chỉ nghe "một tiếng động lớn" rồi tỉnh dậy thấy mình đang nằm trong bệnh viện với một nhóm bác sĩ xung quanh và không biết câu chuyện đang gây xôn xao trên mạng. Ông bị giới truyền thông săn đón đến mức có lúc phải trốn trong nhà.\nNhững tháng đầu sau sự việc trôi qua "rất tồi tệ", ông nói. Dao bị chấn động, rách miệng và mũi, gãy 2 chiếc răng. Ông thậm chí bị các y tá giám sát để tránh trường hợp tự tử và mất nhiều tháng để tập đi lại.\nTrong suốt thời gian nằm viện, ông Dao đã tự động viên mình và hứa với Chúa rằng sẽ đóng góp cho hoạt động thiện nguyện một khi khỏe lại. Sau khi ra viện, ông đã giúp đỡ những người dân ở Texas bị mất nhà cửa do cơn bão Harvey, đến Việt Nam và Campuchia hỗ trợ lắp đặt các tấm năng lượng mặt trời ở những ngôi làng không có điện.\nThậm chí ở vùng Đông Á, mọi người cũng biết tới câu chuyện của ông. Một người đàn ông lớn tuổi đã tiếp cận ông Dao và hỏi "Có phải ông là người trên máy bay không?".\n"Điều đó khiến tôi xúc động", bác sĩ kể, cố nén nước mắt.\nSau cú sốc, ông Dao gặp vấn đề về ngủ, tập trung và cân bằng. Trước sự cố, ông từng tham gia hơn 20 cuộc marathon nhưng bây giờ, ông chỉ có thể chạy bộ chưa đến 5 km, trong đó ít nhất một km là đi bộ.\nUnited Airlines ban đầu cáo buộc ông Dao "hung hăng" nhưng sau đó đã xin lỗi và cam kết tiến hành một cuộc điều tra kỹ lưỡng về sự việc. Oscar Munoz, CEO của hãng, cho biết ông "rất xẩu hổ" khi xem video về ông Dao và khẳng định "việc này sẽ không bao giờ tái diễn".\nKhi được hỏi về cách hành xử của hãng hàng không Mỹ, ông Dao cho rằng các nhân viên lẽ ra có thể giải thích lý do buộc ông rời khỏi chuyến bay một cách thân thiện và thích hợp hơn.\nBác sĩ đã nghỉ hưu nói rằng sự cố xảy ra với ông vẫn có mặt tích cực vì đã buộc United Airlines phải nghiêm túc cân nhắc lại và điều chỉnh các chính sách của họ. "Mọi thứ xảy ra đều có lý do của nó", ông nói.\nSự việc khép lại vài tuần sau đó, khi United Airlines đạt thỏa thuận bồi thường với ông Dao, dù số tiền cụ thể không được công bố. Ông quyết định lên tiếng lần đầu tiên sau 2 năm vì muốn cảm ơn những người ủng hộ mình trên toàn thế giới.\nDao nói ông đã tha thứ cho hãng hàng không cũng như các nhân viên an ninh kéo lê mình. "Tôi không giận họ. Đó là việc họ phải làm. Nếu họ không làm như thế, họ sẽ mất việc", ông nói.',
 'url': 'https://suckhoecongdongonline.vn/bac-si-goc-viet-bi-keo-le-tren-may-bay-my-lan-dau-len-tieng',
 'title': 'Bác sĩ gốc Việt bị kéo lê trên máy bay Mỹ lần đầu lên tiếng | Sức Khỏe Cộng Đồng'}

In [52]:
all_vi_urls = [s.get("url") for s in vi_sentences]

In [69]:
all_zh_urls = [s.get("url") for s in zh_sentences]

In [53]:
len(vi_sentences)

227852

In [70]:
len(all_zh_urls)

219869

In [54]:
all_vi_urls

['https://www.vinmec.com/vie/bai-viet/-u-malt-da-day-phan-1-tong-quan-chan-doan-va-trieu-chung-vi',
 'https://suckhoecongdongonline.vn/0h-hom-nay-26-7-cong-bo-diem-thi-thpt-quoc-gia-2021',
 'https://suckhoedoisong.vn/1-2-so-nguoi-nhiem-omicron-co-the-khong-biet-ban-than-bi-nhiem-benh-169220818200054207.htm',
 'https://medlatec.vn/ba-bau-bi-sung-nuou-rang-trong-cung-nguyen-nhan-trieu-chung-va-cach-dieu-tri',
 'https://thanhnien.vn/-phu-huynh-anh-bo-quen-doi-mat-cua-con-nho-185179557.htm',
 'https://hellobacsi.com/an-uong-lanh-manh/beo-phi/beo-phi/',
 'https://giadinhonline.vn/1-nguoi-chet-18-nguoi-nhap-vien-sau-khi-an-co-o-thai-binh-bac-si-chi-mon-khoai-khau-mang-o-benh-d198531.html',
 'https://bachmai.gov.vn/bai-viet/-nguoi-dan-se-duoc-thu-huong-chat-luong-kham-chua-benh-quoc-te-ngay-tai-benh-vien-bach-mai--9867?id=da6d8b2d-c5bd-c612-e89c-e85f802063b4',
 'https://dantri.com.vn/doi-song/tin-vui-cho-nguoi-lon-tuoi-bi-sa-sut-tri-tue-20200210124423170.htm',
 'https://baohaiphong.vn/1-027-mau-lien-quan-den-benh-vien-phu-san-co-ket-qua-xet-nghiem-am-tinh-voi-vi-rut-sars-cov-2-454175.html',
 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/1-mui-tiem-vac-xin-menactra-gia-bao-nhieu',
 'https://phunusuckhoe.giadinhonline.vn/1-6-benh-nhan-mac-ung-thu-deu-do-viem-5-vi-tri-tren-co-the-bi-viem-canh-bao-ung-thu-dang-den-gan-c12a372458.html',
 'https://baocantho.com.vn/-am-bao-hoc-sinh-sinh-vien-duoc-cham-soc-suc-khoe-toan-dien-a177812.html',
 'https://baonghean.vn/1-000-nguoi-tham-gia-ngay-toan-dan-hien-mau-tinh-nguyen-10135008.html',
 'https://baoangiang.com.vn/-ba-trang-mot-vang-am-tham-gay-hai-than-a363317.html',
 'https://baodanang.vn/1-000-ty-dong-phat-trien-he-thong-benh-vien-risemount-thien-nhan-3244751.html',
 'https://vietnamnet.vn/1-bac-si-va-4-dieu-duong-o-tphcm-bi-tuoc-chung-chi-hanh-nghe-2327070.html',
 'https://youmed.vn/tin-tuc/10-bai-tap-tang-chieu-cao-truoc-khi-di-ngu/',
 'https://baoquangtri.vn/Multimedia/emagazine/202003/o-khu-cach-ly-covid-19-2175387/',
 'https://phuyen.baodaklak.vn/95/100008/ep-nho-khoai-lang/',
 'https://baovinhlong.com.vn/infographics/202109/infographic-thong-diep-5t-phao-dai-chong-dich-covid-19-trong-thoi-gian-tang-cuong-gian-cach-xa-hoi-3076847/',
 'https://www.vietnamplus.vn/10-bai-tap-co-bung-ban-co-the-thuc-hien-trong-khi-xem-netflix-tren-giuong-post978414.vnp',
 'https://vov2.vov.vn/chuyen-tham-kin/dat-the-hang-nhan-tao-dieu-tri-roi-loan-cuong-duong-52966.vov2',
 'https://nhandan.vn/10-he-thong-y-te-viet-nam-co-muc-do-nhan-dien-tot-nhat-voi-nguoi-nuoc-ngoai-post866506.html',
 'https://suckhoeviet.org.vn/03-nguyen-tac-cha-me-can-biet-khi-cho-tre-uong-oresol-5319.html',
 'https://baolangson.vn/1-628-nguoi-hien-mau-hien-tieu-cau-trong-7-ngay-nghi-tet-1644438.html',
 'https://tuoitre.vn/1-000-nguoi-dan-duoc-kham-mien-phi-ai-sap-ho-tro-y-te-co-so-2025080217025175.htm',
 'https://baochinhphu.vn/14-danh-muc-thuoc-nguyen-lieu-lam-thuoc-duoc-xac-dinh-ma-so-hang-hoa-102240617150401244.htm',
 'https://tienphong.vn/100-benh-vien-cong-tai-khanh-hoa-su-dung-benh-an-dien-tu-post1781214.tpo',
 'https://khoahocphothong.vn/03-benh-nhan-may-man-duoc-ghep-giac-mac-mien-phi-tai-bv-fv-237449.html',
 'https://baoquangninh.vn/10-nam-tim-dap-loan-nhip-toi-da-on-dinh-duoc-nhip-tim-nho-cach-nay-3299141.html',
 'https://baogialai.com.vn/1-ca-mac-benh-soi-lay-nhieu-hon-covid-19-post288926.html',
 'https://www.sggp.org.vn/1-hoc-sinh-mac-bach-hau-tu-vong-cach-ly-nhung-nguoi-tiep-xuc-gan-post769781.html',
 'https://baophutho.vn/10-loai-thuc-pham-giup-giam-cholesterol-bao-ve-tim-242164.htm',
 'https://baothanhhoa.vn/11-nhom-nguoi-duoc-bhyt-thanh-toan-100-chi-phi-kham-chua-benh-bhyt-tu-nam-2026-273885.htm',
 'https://www.pharmacity.vn/an-gi-de-thu-thai.htm',
 'https://hanoimoi.vn/12-hoc-sinh-tieu-hoc-nhap-vien-sau-khi-an-com-nam-ngoai-truong-698325.html',
 'https://baotayninh.vn/10-thuc-pham-lanh-manh-nhat-giup-cai-thien-suc-khoe-toan-dien-139587.html',
 'https://www.qdnd.vn/80-nam-cach-mang-thang-tam-va-quoc-khanh-2-9/bao-hiem-y-te-toan-dan-chinh-sach-nhan-van-trong-ky-nguyen-moi-844035',
 'https://mega.vietnamplus.vn/theo-chan-nguoi-dan-bien-vien-mien-tay-xu-nghe-xuyen-rung-hai-loc-troi-5412.html',
 'https://vnexpress.net/10-000-don-vi-mau-hien-kip-bo-sung-cho-dieu-tri-sau-tet-5046292.html',
 'https://thanhnien.vn/1-chen-dau-tay-moi-ngay-giup-giam-mo-mau-lai-tot-cho-tim-nao-185241110173604538.htm',
 'https://suckhoecongdongonline.vn/1-chien-si-gap-tai-nan-tren-duong-chua-chay-tai-kcn-thuy-van',
 'https://suckhoedoisong.vn/1-gio-cuu-song-thanh-cong-tre-so-sinh-bi-ngat-trang-do-sa-day-rau-169220907120520442.htm',
 'https://www.vinmec.com/vie/bai-viet/1-lan-xa-tri-bao-nhieu-tien-giai-dap-thac-mac-ve-chi-phi-xa-tri',
 'https://benhviennhitrunguong.gov.vn/11724.html',
 'https://medlatec.vn/benh-vui-duong-vat-nguyen-nhan-trieu-chung-va-phuong-phap-dieu-tri-hieu-qua',
 'https://hellobacsi.com/an-uong-lanh-manh/beo-phi/lam-the-nao-de-co-the-tu-tinh-chi-so-bmi/',
 'https://bachmai.gov.vn/bai-viet/1-5-ty-dong-tri-lieu-ung-thu-bang-vac-xin-giam-doc-benh-vien-ung-buou-noi-gi?id=432373c8-00c6-5132-fcbf-ecf40c371c67',
 'https://dantri.com.vn/khoa-hoc/khoa-hoc-phat-hien-cach-xac-dinh-ca-phe-nao-co-the-tot-hon-cho-suc-khoe-20260206235302566.htm',
 'https://giadinhonline.vn/1-tuan-xuong-3kg-thuoc-giam-can-nao-bang-ly-nuoc-nay-d87290.html',
 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/1-ngay-an-2-bua-co-giam-can-khong-goc-nhin-khoa-hoc',
 'https://baodanang.vn/1-172-can-bo-cong-chuc-lam-viec-tai-trung-tam-hanh-chinh-thanh-pho-am-tinh-voi-sars-cov-2-3244280.html',
 'https://baohaiphong.vn/1-088-nguoi-nhap-vien-do-tai-nan-giao-thong-262405.html',
 'https://vietnamnet.vn/1-nguoi-tu-vong-4-ca-cap-cuu-loi-canh-bao-ve-mon-an-chet-nguoi-2360557.html#comment',
 'https://baonghean.vn/1-5-so-nguoi-tu-vong-tren-the-gioi-la-do-thit-do-va-nuoc-ngot-10084287.html',
 'https://phunusuckhoe.giadinhonline.vn/1-bo-rau-diep-ca-3-cach-tri-mun-sau-7-ngay-vet-tham-nam-tan-bien-da-trang-min-c12a99808.html',
 'https://baocantho.com.vn/-an-nghi-tren-cung-trang-a53252.html',
 'https://baoangiang.com.vn/-la-chan-phong-chong-dich-benh-a427295.html',
 'https://vov2.vov.vn/chuyen-tham-kin/phat-hien-keo-ngam-dieu-tri-chung-liet-duong-o-nam-gioi-chua-chat-cam-41531.vov2',
 'https://phuyen.baodaklak.vn/95/100077/bao-luc-doi-voi-phu-nu-da-tro-thanh-van-de-suc-khoe-mang-tinh-toan-cau/',
 'https://baovinhlong.com.vn/phong-su-anh/201608/anh-nhung-nguoi-khong-nen-an-toi-2724729/',
 'https://www.vietnamplus.vn/10-dau-hieu-canh-bao-co-the-ban-dang-tieu-thu-qua-nhieu-duong-post1015040.vnp',
 'https://suckhoeviet.org.vn/10-bai-thuoc-hay-theo-y-hoc-co-truyen-tu-rau-ngo-9122.html',
 'https://nhandan.vn/100-co-so-y-te-o-can-tho-trien-khai-benh-an-dien-tu-post912931.html',
 'https://baogialai.com.vn/1-phu-nu-nguy-kich-do-ngo-doc-thuoc-gay-te-nho-rang-post270107.html',
 'https://baochinhphu.vn/2-hinh-thuc-ho-tro-thuoc-mien-phi-cho-nguoi-benh-102221018151735238.htm',
 'https://tuoitre.vn/1-hoc-sinh-o-phu-quoc-tu-vong-nghi-bi-mac-benh-viem-nao-mo-cau-20260318174515251.htm',
 'https://tienphong.vn/14-nguoi-tai-hue-nhap-vien-nghi-ngo-doc-do-an-banh-mi-post1781726.tpo',
 'https://www.qdnd.vn/80-nam-trien-lam-thanh-tuu-dat-nuoc-hanh-trinh-doc-lap-tu-do-hanh-phuc/trai-nghiem-y-te-thong-minh-hien-dai-tai-khong-gian-trien-lam-cua-bo-y-te-843959',
 'https://baoquangninh.vn/15-dan-so-toan-tinh-co-ho-so-dien-tu-quan-ly-suc-khoe-2363673.html',
 'https://vnexpress.net/10-gio-mo-cuu-ca-ung-thu-hoc-mui-chua-tung-co-5046721.html',
 'https://youmed.vn/tin-tuc/10-dau-hieu-sap-co-kinh-nguyet-ma-chi-em-nen-biet/',
 'https://benhvienvietduc.org/4-phuong-phap-can-thiep-ngoai-khoa-dieu-tri-benh-tri.html',
 'https://khoahocphothong.vn/1-trieu-nguoi-nam-my-nhiem-benh-chikungunya-dau-nhuc-du-doi-238557.html',
 'https://benhviennhitrunguong.gov.vn/16924.html',
 'https://www.sggp.org.vn/100-nguoi-dan-duoc-kham-suc-khoe-dinh-ky-vao-nam-2026-muc-tieu-va-thuc-te-con-cach-xa-post804791.html',
 'https://baophutho.vn/10-loai-thuc-pham-va-do-uong-giup-lan-da-sang-khoe-234590.htm',
 'https://hanoimoi.vn/20-nam-cho-doi-va-cu-hoi-sinh-nu-cuoi-bang-ky-thuat-vi-phau-phuc-tap-737553.html',
 'https://baoquangtri.vn/Multimedia/truyen-hinh/202003/viet-nam-quyet-tam-chien-thang-dai-dich-covid-19-2175634/',
 'https://baothanhhoa.vn/450-can-bo-chien-si-cong-an-tinh-thanh-hoa-tham-gia-hien-mau-tinh-nguyen-281469.htm',
 'https://baotayninh.vn/12-can-duoc-dau-tu-tren-30-ty-dong-nang-cap-xay-moi-trung-tam-y-te-can-duoc-co-so-ii-116864.html',
 'https://thaythuocvietnam.vn/10-cong-thuc-lam-trang-da-bang-sua-chua-khong-duong/',
 'https://www.pharmacity.vn/benh-vien-pham-ngoc-thach.htm',
 'https://baolangson.vn/100-benh-vien-phai-trien-khai-benh-an-dien-tu-truoc-thang-10-2025-5041492.html',
 'https://www.vinmec.com/vie/bai-viet/10-bai-tap-cho-tren-nu-ma-ban-nhat-dinh-phai-thu-vi',
 'https://thanhnien.vn/1-muong-toi-ngam-mat-ong-moi-ngay-dieu-gi-xay-ra-voi-duong-huyet-va-huyet-ap-185250916231920254.htm',
 'https://hellobacsi.com/an-uong-lanh-manh/beo-phi/nguoi-beo-phi/',
 'https://medlatec.vn/block-nhanh-phai-la-benh-ly-gi-va-viec-dieu-tri-co-phuc-tap-khong',
 'https://suckhoedoisong.vn/1-nguoi-tu-vong-do-sot-xuat-huyet-dak-lak-canh-bao-nguy-co-co-them-nhieu-benh-nhan-169230713145618154.htm',
 'https://suckhoecongdongonline.vn/1-lit-xang-co-den-hon-5-bo-nganh-cung-quan-ly',
 'https://dantri.com.vn/khoa-hoc/nghien-cuu-moi-loai-chat-trong-com-giup-chong-2-loai-benh-thoi-dai-20260130162757694.htm',
 'https://bachmai.gov.vn/bai-viet/10-cach-ngan-ngua-ung-thu?id=0b46fd9a-8ae4-309b-7448-52675fe4d668',
 'https://giadinhonline.vn/10-bi-quyet-lam-dep-cua-phu-nu-nhat-ban-giup-ban-tre-ra-ca-chuc-tuoi-d151734.html',
 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/1-phut-plank-dot-bao-nhieu-calo-su-that-ve-hieu-qua-giam-can-ban-can-biet',
 'https://phunusuckhoe.giadinhonline.vn/1-chiec-quan-jean-ong-loe-1001-cach-phoi-do-ngay-he-cuc-thoi-thuong-tre-trung-c12a280816.html',
 'https://baonghean.vn/1-phu-nu-bi-ran-cap-nia-can-tu-vong-10228129.html',
 'https://baohaiphong.vn/1-277-nguoi-duoc-tiem-mui-2-vaccine-astrazeneca-dot-5-183460.html',
 'https://baocantho.com.vn/-ap-ung-nhu-cau-sang-loc-chan-doan-truoc-sinh-va-so-sinh-vung-bscl-a60427.html',
 'https://vov2.vov.vn/doi-song-xa-hoi/giam-can-an-toan-don-tet-57110.vov2',
 'https://baodanang.vn/1-500-dai-bieu-du-hoi-nghi-kiem-soat-nhiem-khuan-khu-vuc-chau-a-3241330.html',
 'https://phuyen.baodaklak.vn/95/100300/mot-truong-hop-tu-vong-do-sot-xuat-huyet/',
 'https://www.vietnamplus.vn/10-loai-thuc-pham-giup-xuong-chac-khoe-phong-ngua-loang-xuong-hieu-qua-post1072773.vnp',
 'https://nhandan.vn/1000-nguoi-di-bo-dong-hanh-nang-cao-nhan-thuc-cong-dong-ve-benh-dot-quy-post847836.html',
 'https://baogialai.com.vn/1-san-pham-cham-soc-da-bi-thu-hoi-do-cong-thuc-khong-dung-ho-so-cong-bo-post276506.html',
 'https://tienphong.vn/19-nguoi-nghi-ngo-doc-sau-khi-an-banh-mi-tai-dong-thap-post1823388.tpo',
 'https://suckhoeviet.org.vn/10-bi-quyet-lam-dep-tu-nhien-cho-phai-nu-17188.html',
 'https://baoangiang.com.vn/-nguye-n-dem-he-t-kha-nang-de-phuc-vu-cham-so-c-va-hoan-thie-n-ne-t-de-p-vie-t--a258519.html',
 'https://baovinhlong.com.vn/phong-su-anh/201610/anh-nhung-sai-lam-khien-ban-dang-pha-huy-giac-ngu-cua-minh-2745995/',
 'https://www.qdnd.vn/chinh-tri/tin-tuc/sua-doi-luat-duoc-dai-bieu-quoc-hoi-lo-ngai-ve-nguy-co-doc-quyen-thuoc-tren-thi-truong-799764',
 'https://tuoitre.vn/10-khuyen-cao-cua-chuyen-gia-de-bao-ve-tim-mach-cho-nguoi-cao-tuoi-2025112615394966.htm',
 'https://vietnamnet.vn/1-trieu-lieu-vac-xin-moderna-do-my-trao-tang-ve-den-ha-noi-794048.html',
 'https://youmed.vn/tin-tuc/10-loi-ich-khong-ngo-cua-yoga-doi-voi-suc-khoe/',
 'https://khoahocphothong.vn/10-diem-moi-cua-chuong-trinh-phong-chong-covid-19-236491.html',
 'https://baoquangninh.vn/2-tre-tu-vong-sau-tiem-vaccine-khong-lien-quan-den-vaccine-va-thuc-hanh-tiem-chung-3164367.html',
 'https://www.pharmacity.vn/cach-nau-nuoc-dashi-rau-cu-cho-be-5-thang-tuoi.htm',
 'https://baochinhphu.vn/3-benh-nhan-tu-vong-do-an-phai-nam-doc-102230720184028848.htm',
 'https://benhviennhitrunguong.gov.vn/3-truong-hop-tre-nhap-vien-trong-tinh-trang-nguy-kich-do-bi-ong-dot.html',
 'https://baophutho.vn/10-mon-an-nhe-buoi-toi-giup-ngu-ngon-hon-246065.htm',
 'https://www.sggp.org.vn/194-hoc-sinh-thi-chon-doi-tuyen-olympic-quoc-te-va-khu-vuc-post844487.html',
 'https://thaythuocvietnam.vn/10-kha-nang-sieu-viet-cua-co-nguoi/',
 'https://baothanhhoa.vn/75-nam-viet-nam-dong-hanh-cung-to-chuc-y-te-the-gioi-249113.htm',
 'https://baotayninh.vn/20-benh-nen-co-nguy-co-gia-tang-muc-do-nang-khi-mac-covid-19-31512.html',
 'https://baolangson.vn/12-ca-ghep-giac-mac-thanh-cong-bang-nguon-mo-hien-tang-tu-nepal-5067486.html',
 'https://benhvienvietduc.org/6-nguyen-nhan-thuong-gap-gay-dau-hau-mon.html',
 'https://hanoimoi.vn/4-ngay-duy-nhat-kham-suc-khoe-tai-nha-chi-760-000-dong-cung-medlatec-707058.html',
 'https://vnexpress.net/10-nguoi-ngo-doc-sau-bua-an-tet-voi-trung-ca-sau-hoa-tien-5042845.html',
 'https://baoquangtri.vn/chinh-tri/202202/nganh-y-te-doi-moi-co-che-tu-chu-tai-chinh-nang-cao-hieu-qua-hoat-dong-2198207/',
 'https://www.vinmec.com/vie/bai-viet/10-bien-phap-khac-phuc-tai-nha-de-co-lan-da-tuoi-sang-cang-bong-vi',
 'https://medlatec.vn/cac-loai-thuoc-tri-chay-ran-pho-bien-va-luu-y-khi-dung',
 'https://hellobacsi.com/an-uong-lanh-manh/beo-phi/thuc-don-cho-nguoi-beo-phi/',
 'https://thanhnien.vn/1-nguoi-chet-12-nguoi-nhap-vien-sau-khi-an-gio-185418718.htm',
 'https://suckhoedoisong.vn/1-nhan-vien-bi-thuong-tai-san-mot-co-so-y-te-bi-hu-hong-do-mua-lu-o-dien-bien-169240726080202412.htm',
 'https://suckhoecongdongonline.vn/1-ngay-4-tre-so-sinh-tu-vong-tai-benh-vien-san-nhi-tinh-bac-ninh',
 'https://bachmai.gov.vn/bai-viet/10-luu-y-cua-benh-nhan-chay-than-nhan-tao-trong-mua-covid-19?id=c06a3eb6-6a71-642e-3870-cfc1be979326',
 'https://dantri.com.vn/khoa-hoc/sap-thu-nghiem-thuoc-ung-thu-do-ai-thiet-ke-tren-nguoi-20250716132233915.htm',
 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/1-tuan-nen-uong-bao-nhieu-vien-c-sui-huong-dan-su-dung-an-toan',
 'https://giadinhonline.vn/10-bieu-hien-nguy-hiem-va-5-nguyen-tac-phong-benh-tre-sot-sieu-vi-d157819.html',
 'https://vietnamnet.vn/10-bai-thuoc-tu-hoa-du-du-duc-ho-tro-suc-khoe-2434995.html',
 'https://baohaiphong.vn/1-360-nguoi-nhap-canh-tu-ngay-8-3-225133.html',
 'https://baonghean.vn/10-bai-thuoc-chua-benh-tu-cay-nho-noi-10010776.html',
 'https://phunusuckhoe.giadinhonline.vn/1-cu-khoai-tay-3-cach-xoa-mo-dom-den-dieu-tri-tan-goc-mun-va-loai-bo-hoan-toan-khuyet-diem-giup-da-dep-khong-ti-vet-c12a304360.html',
 'https://baocantho.com.vn/-au-phong-rang-it-muoi-giup-giam-can-ha-huyet-ap-hieu-qua-a149792.html',
 'https://baodanang.vn/10-3-ty-dong-phong-va-tri-lieu-roi-nhieu-tam-tri-cho-nguoi-tam-than-3088942.html',
 'https://benhvienvietduc.org/bac-si-benh-vien-hn-viet-duc-canh-bao-benh-ly-khop-gia-xuong-thuyen.html',
 'https://youmed.vn/tin-tuc/10-thuc-pham-cho-nguoi-cao-huyet-ap-ma-co-the-ban-chua-biet/',
 'https://baoangiang.com.vn/-thoi-gian-vang-trong-cap-cuu-dot-quy-a342639.html',
 'https://suckhoeviet.org.vn/10-cong-dung-chua-benh-tu-cay-bi-do-21739.html',
 'https://vov2.vov.vn/doi-song-xa-hoi/phong-tranh-dich-noi-cong-cong-cho-thay-binh-an-ma-chu-quan-23836.vov2',
 'https://phuyen.baodaklak.vn/95/100384/nhung-loai-rau-cu-co-tinh-khang-viem-cao/',
 'https://www.vietnamplus.vn/10-loai-trai-cay-giup-bo-sung-protein-tu-nhien-tot-cho-tim-va-tieu-hoa-post1070278.vnp',
 'https://baovinhlong.com.vn/phong-su-anh/201701/nhung-huu-ich-cua-qua-quat-doi-voi-suc-khoe-2776963/',
 'https://nhandan.vn/11-nguoi-o-bac-kan-ngo-doc-cu-au-tau-post788270.html',
 'https://baochinhphu.vn/3-nguyen-nhan-chinh-lam-gia-tang-benh-khong-lay-nhiem-102220811151836436.htm',
 'https://www.sggp.org.vn/2-san-pham-thuc-pham-bao-ve-suc-khoe-co-chat-cam-sibutramine-post793491.html',
 'https://baophutho.vn/1000-ngay-vang-chia-khoa-cho-chieu-cao-tri-tue-va-mien-dich-vuot-troi-242717.htm',
 'https://www.qdnd.vn/nuoi-duong-van-hoa-bo-doi-cu-ho/benh-vien-quan-y-87-chung-tay-cung-nhan-dan-vung-lu-1013453',
 'https://baogialai.com.vn/10-thuc-pham-lanh-manh-nhat-giup-cai-thien-suc-khoe-toan-dien-post580530.html',
 'https://tienphong.vn/2-ca-ghep-tang-xuyen-dem-gianh-lai-su-song-tu-tu-than-post1810684.tpo',
 'https://baoquangninh.vn/22-duong-day-nong-tiep-nhan-thong-tin-ve-dich-benh-do-virus-corona-2469337.html',
 'https://baolangson.vn/2-320-nguoi-duoc-xet-nghiem-sang-loc-lao-mien-phi-5032047.html',
 'https://tuoitre.vn/100-benh-vien-tp-hcm-phai-nghiem-tuc-tham-gia-he-thong-tiep-nhan-va-phan-anh-cua-nguoi-dan-20251222153958685.htm',
 'https://khoahocphothong.vn/10-hoat-dong-noi-bat-cua-benh-vien-nhi-dong-1-nam-2010-240915.html',
 'https://baoquangtri.vn/chinh-tri/202305/hon-116-nghin-ty-dong-duoc-huy-dong-vao-quy-vaccine-phong-covid-19-2209565/',
 'https://baothanhhoa.vn/bac-si-canh-bao-vi-sao-nen-can-trong-khi-su-dung-nuoc-gieng-de-nau-an-253034.htm',
 'https://baotayninh.vn/3-loai-rau-de-tim-la-than-duoc-cho-than-yeu-138091.html',
 'https://hanoimoi.vn/8-nguyen-tac-vang-uong-ruou-bia-an-toan-trong-dip-tet-734223.html',
 'https://www.vinmec.com/vie/bai-viet/10-cach-de-tang-cuong-kha-nang-sinh-san-cua-nam-gioi-va-tang-so-luong-tinh-trung-vi',
 'https://medlatec.vn/cac-vi-tri-dau-dau-nguy-hiem-va-cach-xu-ly',
 'https://suckhoedoisong.vn/1-trong-3-benh-nhan-cua-vu-chay-nha-tro-o-trung-kinh-duoc-chuyen-thang-len-phong-hoi-suc-tich-cuc-bv-bach-mai-169240524180328332.htm',
 'https://www.pharmacity.vn/chieu-dai-phoi-thai-7-tuan-tuoi-la-bao-nhieu.htm',
 'https://hellobacsi.com/an-uong-lanh-manh/bi-quyet-an-uong-lanh-manh/10-thuc-pham-an-khong-dung-cach/',
 'https://thanhnien.vn/1-nguoi-tu-vong-11-nguoi-nhap-vien-o-vung-nghi-la-o-dich-bach-hau-185880140.htm',
 'https://thaythuocvietnam.vn/10-nguyen-nhan-gay-rong-kinh-chi-em-phu-nu-can-biet/',
 'https://benhviennhitrunguong.gov.vn/5-nguyen-tac-bo-tui-cha-me-can-biet-khi-dua-tre-di-kham-benh.html',
 'https://suckhoecongdongonline.vn/1-san-phu-de-rot-tren-xe-grab-khi-dang-tren-duong-toi-benh-vien',
 'https://dantri.com.vn/phap-luat/bo-cong-an-khoi-to-kham-xet-nha-vien-truong-vien-y-duoc-hoc-dan-toc-tphcm-20241122133225902.htm',
 'https://bachmai.gov.vn/bai-viet/100-ca-san-phu-co-thai-mac-sot-xuat-huyet-da-duoc-dieu-tri-an-toan?id=e0035a59-1963-1aeb-b1a1-edbc36c1bc0c',
 'https://phunusuckhoe.giadinhonline.vn/1-gio-nhin-cham-cham-vao-man-hinh-lam-tang-20-nguy-co-can-thi-c12a501011.html',
 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/10-cach-giam-dau-lung-cho-ba-bau-duoc-nhieu-me-ap-dung',
 'https://giadinhonline.vn/10-cach-dien-quan-short-tre-trung-va-tinh-te-phu-hop-voi-phu-nu-u40-d197990.html',
 'https://vietnamnet.vn/10-ca-tu-vong-khi-sot-xuat-huyet-bung-phat-tphcm-khuyen-khich-dan-tiem-vac-xin-2427465.html',
 'https://baohaiphong.vn/1-492-mau-xet-nghiem-cua-cong-nhan-tai-cam-giang-am-tinh-voi-sars-cov-2-198647.html',
 'https://baonghean.vn/10-bi-kip-cham-soc-da-hang-ngay-10017181.html',
 'https://vov2.vov.vn/suc-khoe/0h00-ngay-266-ha-noi-cho-phep-nguoi-dan-tham-gia-hoat-dong-the-thao-ngoai-troi-27021.vov2',
 'https://baodanang.vn/10-cach-hieu-qua-de-lam-cho-khuon-mat-trong-tre-lai-mot-lan-nua-3241117.html',
 'https://baocantho.com.vn/-ay-manh-truyen-thong-ve-hiv-den-cong-nhan-nguoi-lao-dong-a169428.html',
 'https://benhvienvietduc.org/bac-si-nhi-chi-ro-3-benh-giao-mua-tre-em-hay-gap-phai-cha-can-luu-y.html',
 'https://phuyen.baodaklak.vn/95/100525/nhieu-cap-nganh-cung-hanh-dong/',
 'https://youmed.vn/tin-tuc/11-loi-ich-cua-vitamin-c-cho-lan-da-va-cach-su-dung/',
 'https://baoangiang.com.vn/-vacxin-sputnik-v-cua-nga-nhan-duoc-su-ung-ho-tu-nhieu-nuoc-tay-au-a297126.html',
 'https://www.vietnamplus.vn/10-phuong-phap-bao-ve-suc-khoe-trong-mua-bao-lut-va-mua-lu-post977783.vnp',
 'https://suckhoeviet.org.vn/10-loai-thao-duoc-giup-tang-cuong-suc-khoe-va-lam-dep-16972.html',
 'https://baovinhlong.com.vn/phong-su-anh/201702/nam-gioi-bi-than-hu-nen-an-gi-2785468/',

In [62]:
all_vi_urls[0].split("//")[1].split("/")[0]

'www.vinmec.com'

In [71]:
all_zh_urls[0].split("//")[1].split("/")[0]

'www.a-hospital.com'

In [78]:
zh_domains = []
for url in all_zh_urls:
    zh_domains.append(url.split("//")[1].split("/")[0])

In [79]:
set(zh_domains)

{'ask.39.net',
 'ask.familydoctor.com.cn',
 'baby.39.net',
 'bachmai.gov.vn',
 'baidianfeng.familydoctor.com.cn',
 'baodanang.vn',
 'byby.39.net',
 'cancer.39.net',
 'care.39.net',
 'ek.39.net',
 'fitness.39.net',
 'fk.39.net',
 'fk.99.com.cn',
 'food.39.net',
 'gan.39.net',
 'gc.39.net',
 'gk.39.net',
 'health.people.com.cn',
 'heart.39.net',
 'hellobacsi.com',
 'jb39.com',
 'jbk.39.net',
 'man.39.net',
 'nk.39.net',
 'pf.39.net',
 'qihuangzhishu.com',
 'qy.familydoctor.com.cn',
 'shen.39.net',
 'sj.39.net',
 'suckhoedoisong.vn',
 'suckhoeviet.org.vn',
 'test.pmphai.com',
 'thaythuocvietnam.vn',
 'tnb.39.net',
 'v.familydoctor.com.cn',
 'wei.39.net',
 'woman.39.net',
 'www.120ask.com',
 'www.a-hospital.com',
 'www.baidu.com',
 'www.cnkang.com',
 'www.familydoctor.cn',
 'www.familydoctor.com.cn',
 'www.msdmanuals.cn',
 'www.vinmec.com',
 'www.wujue.com',
 'www.youlai.cn',
 'www.zydcd.com',
 'yanglao.familydoctor.com.cn',
 'ypk.familydoctor.com.cn',
 'zhongyibaodian.net'}

In [75]:
vi_domains = []
for url in all_vi_urls:
    vi_domains.append(url.split("//")[1].split("/")[0])

In [76]:
set(vi_domains)

{'bachmai.gov.vn',
 'baoangiang.com.vn',
 'baocantho.com.vn',
 'baochinhphu.vn',
 'baodanang.vn',
 'baogialai.com.vn',
 'baohaiphong.vn',
 'baolangson.vn',
 'baonghean.vn',
 'baophutho.vn',
 'baoquangninh.vn',
 'baoquangtri.vn',
 'baotayninh.vn',
 'baothanhhoa.vn',
 'baovinhlong.com.vn',
 'benhviennhitrunguong.gov.vn',
 'benhvienvietduc.org',
 'dantri.com.vn',
 'giadinhonline.vn',
 'hanoimoi.vn',
 'hellobacsi.com',
 'khoahocphothong.vn',
 'medlatec.vn',
 'mega.vietnamplus.vn',
 'nhandan.vn',
 'phunusuckhoe.giadinhonline.vn',
 'phuyen.baodaklak.vn',
 'special.vietnamplus.vn',
 'suckhoecongdongonline.vn',
 'suckhoedoisong.vn',
 'suckhoeviet.org.vn',
 'thanhnien.vn',
 'thaythuocvietnam.vn',
 'tiemchunglongchau.com.vn',
 'tienphong.vn',
 'tuoitre.vn',
 'vietnamnet.vn',
 'vnexpress.net',
 'vov2.vov.vn',
 'www.pharmacity.vn',
 'www.qdnd.vn',
 'www.sggp.org.vn',
 'www.vietnamplus.vn',
 'www.vinmec.com',
 'youmed.vn'}

In [ ]:
vi_sentences[10]

{'text': 'Tiêm vắc xin Menactra là một giải pháp giúp bảo vệ cơ thể khỏi các bệnh do vi khuẩn não mô cầu Neisseria meningitidis gây ra, bao gồm viêm màng não, nhiễm trùng huyết và viêm phổi. Vắc xin viêm màng não này đặc biệt hiệu quả trong việc phòng ngừa các chủng vi khuẩn thuộc nhóm huyết thanh A, C, Y, W-135, những chủng có thể gây bệnh nghiêm trọng nếu không được điều trị kịp thời.\n1 mũi tiêm vắc xin Menactra giá bao nhiêu?\nVắc xin Menactra tại Trung tâm Tiêm chủng Long Châu có giá 1.360.000 VNĐ, nhưng có thể thay đổi tùy thời điểm. Tuy nhiên, mức giá này có thể thay đổi tùy vào thời điểm, tình trạng cung ứng vắc xin và các chương trình ưu đãi tại các cơ sở tiêm chủng. Do vậy, nếu bạn đang lên kế hoạch tiêm vắc xin này, hãy liên hệ hotline 18006928 để được tư vấn cụ thể và chính xác nhất nhé!\nKhi bạn quyết định tiêm vắc xin Menactra để phòng ngừa các bệnh do vi khuẩn não mô cầu Neisseria meningitidis gây ra, một trong những yếu tố mà bạn chắc chắn sẽ quan tâm là giá của loại vắc xin này. Vắc xin Menactra được sử dụng chủ yếu để bảo vệ cơ thể khỏi các bệnh xâm lấn, đặc biệt là viêm màng não, nhiễm trùng huyết, và viêm phổi do các nhóm vi khuẩn não mô cầu A, C, Y và W-135 gây ra. Đây là một vắc xin quan trọng, đặc biệt đối với trẻ em từ 9 tháng tuổi đến người trưởng thành dưới 56 tuổi, và rất cần thiết cho những người sống trong môi trường tập thể hoặc có nguy cơ cao mắc các bệnh này.\nVắc xin Menactra thường được tiêm 02 liều cơ bản đối với trẻ tròn 09 tháng đến < 24 tháng tuổi:\n- Mũi 1: Lần đầu tiên.\n- Mũi 2: 3 tháng sau mũi 1.\nĐối với người từ 2 tuổi đến 55 tuổi:\n- Tiêm 1 liều duy nhất.\nTiêm chủng nhắc lại: Có thể tiêm nhắc lại ít nhất 4 năm sau mũi tiêm gần nhất cho người từ 15 đến 55 tuổi nếu tiếp tục có nguy cơ mắc não mô cầu hoặc cần để đi du học, nhập cư.\nVắc xin Menactra có tác dụng gì?\nVắc xin Menactra là một loại vắc xin quan trọng được sử dụng để phòng ngừa các bệnh do vi khuẩn não mô cầu gây ra, đặc biệt là các tuýp A, C, Y và W-135. Đây là những chủng vi khuẩn có thể gây ra các bệnh nguy hiểm như viêm màng não và nhiễm trùng huyết, có thể dẫn đến các biến chứng nghiêm trọng và thậm chí tử vong nếu không được điều trị kịp thời.\nVắc xin Menactra không chỉ giúp bảo vệ khỏi các chủng vi khuẩn A và C, mà còn phòng ngừa được thêm hai chủng vi khuẩn khác là Y và W-135. Điều này giúp mở rộng phạm vi bảo vệ, tạo sự an tâm lớn hơn cho người sử dụng, đặc biệt là trong bối cảnh bệnh viêm màng não mô cầu có thể xảy ra bất cứ lúc nào, đặc biệt là ở những khu vực đông người hoặc những người có nguy cơ cao mắc bệnh. Với khả năng bảo vệ rộng hơn, vắc xin Menactra giúp giảm thiểu tối đa nguy cơ mắc bệnh từ các tuýp vi khuẩn não mô cầu này.\nMột trong những ưu điểm nổi bật của vắc xin Menactra là nó có thể được tiêm sớm hơn, bắt đầu từ trẻ em từ 9 tháng tuổi, giúp tạo miễn dịch sớm và bảo vệ trẻ khỏi các bệnh nghiêm trọng ngay từ khi còn nhỏ. Đây là một sự cải tiến quan trọng so với các loại vắc-xin trước đó, giúp hệ miễn dịch của trẻ có thể chống lại các tác nhân gây bệnh trước khi chúng có cơ hội xâm nhập vào cơ thể.\nNgoài ra, vắc xin Menactra còn được biết đến với tính an toàn cao, ít gây ra tác dụng phụ so với các loại vắc xin khác. Những phản ứng sau tiêm thường chỉ là các triệu chứng nhẹ như đau tại vết tiêm hoặc cảm giác mệt mỏi, và chúng sẽ tự khỏi trong vòng vài ngày mà không cần điều trị đặc biệt. Điều này giúp phụ huynh và người tiêm chủng cảm thấy an tâm hơn khi lựa chọn loại vắc xin này.\nPhản ứng sau khi tiêm vắc xin Menactra\nSau khi tiêm vắc xin phòng bệnh Menactra, hầu hết mọi người, đặc biệt là trẻ em, sẽ gặp phải một số phản ứng nhẹ. Đây là biểu hiện bình thường của quá trình đáp ứng miễn dịch của cơ thể đối với vắc xin và không gây ra mối nguy hiểm đáng lo ngại. Các phản ứng này thường tự khỏi trong vòng vài ngày mà không cần điều trị đặc biệt.\nĐối với trẻ em từ 9 tháng đến 12 tháng tuổi, phản ứng sau tiêm thường khá nhẹ. Trẻ có thể cảm thấy đau nhức nhẹ tại vị trí tiêm, kèm theo cảm giác cáu kỉnh và quấy khóc. Đây là phản ứng bình thường của cơ thể khi tiếp xúc với vắc xin và không kéo dài lâu, thường chỉ trong một ngày hoặc hai ngày sau tiêm. Việc cáu kỉnh ở trẻ nhỏ có thể là do cảm giác khó chịu tại vị trí tiêm hoặc mệt mỏi, và sẽ giảm dần sau khi trẻ nghỉ ngơi.\nĐối với trẻ em từ 2 tuổi đến 10 tuổi, các phản ứng có thể đa dạng hơn. Trẻ có thể cảm thấy đau tại vết tiêm, cáu kỉnh và có thể xuất hiện các triệu chứng khác như tiêu chảy, ngủ gà gật, hoặc chán ăn. Các triệu chứng này thường không kéo dài lâu và sẽ tự hết sau vài ngày mà không cần điều trị. Mặc dù một số trẻ có thể cảm thấy mệt mỏi hoặc khó chịu, nhưng các triệu chứng này là một phần của quá trình miễn dịch và không gây nguy hiểm cho sức khỏe của trẻ.\nĐối với người từ 11 tuổi đến 55 tuổi, phản ứng sau tiêm thường bao gồm cảm giác đau tại vị trí tiêm, cáu kỉnh, đau đầu và mệt mỏi. Những triệu chứng này cũng thường nhẹ và sẽ hết trong vòng vài ngày mà không cần sử dụng thuốc đặc biệt. Đôi khi, một số người có thể cảm thấy hơi chóng mặt hoặc khó chịu, nhưng đây cũng là phản ứng bình thường khi cơ thể bắt đầu sản sinh kháng thể chống lại các vi khuẩn gây bệnh.\nNhìn chung, các phản ứng sau tiêm vắc xin Menactra đều là những triệu chứng nhẹ và tự khỏi. Các triệu chứng này có thể xảy ra trong vòng 7 ngày sau khi tiêm và không cần can thiệp điều trị đặc biệt. Tuy nhiên, nếu bạn hoặc trẻ có bất kỳ triệu chứng bất thường nào như sốt cao kéo dài, phát ban, hoặc có phản ứng nghiêm trọng tại vị trí tiêm, bạn nên liên hệ ngay với bác sĩ hoặc đến các cơ sở y tế để được tư vấn và xử lý kịp thời.\nViệc theo dõi các phản ứng sau tiêm và chăm sóc hợp lý sẽ giúp quá trình hồi phục nhanh chóng, đồng thời bảo vệ sức khỏe của người bệnh.\nHy vọng qua nội dung bài viết bạn đã có thêm thông tin về chi phí tiêm vắc xin Menactra giá bao nhiêu? Chi phí tiêm vắc xin Menactra có thể thay đổi tùy theo từng thời điểm và các chương trình ưu đãi tại các Trung tâm Tiêm chủng Long Châu, nhưng mức giá trung bình dao động khoảng 1.360.000 VNĐ mỗi liều. Mặc dù chi phí có thể là một yếu tố cần cân nhắc, nhưng vắc xin Menactra là một khoản đầu tư xứng đáng để bảo vệ sức khỏe bản thân và gia đình trước các bệnh nguy hiểm do vi khuẩn não mô cầu. Ngoài ra, việc tiêm vắc xin này sẽ giúp bạn yên tâm hơn trong việc phòng ngừa và bảo vệ sức khỏe lâu dài, đặc biệt là trong các môi trường có nguy cơ cao.\nBên cạnh vắc xin Menactra, MenQuadfi là một lựa chọn vắc xin liên hợp thế hệ mới hiện đang được triển khai tại Trung tâm Tiêm chủng Long Châu. Vắc xin này sử dụng polysaccharide các nhóm huyết thanh A, C, Y và W-135 của vi khuẩn Neisseria meningitidis, kết hợp với giải độc tố uốn ván, giúp tạo đáp ứng miễn dịch chủ động và bền vững. MenQuadfi được chỉ định cho trẻ từ 6 tuần tuổi trở lên và người lớn. Đây là lựa chọn phù hợp trong bối cảnh các chủng vi khuẩn não mô cầu như Y và W-135 đang có xu hướng gia tăng, đồng thời đáp ứng nhu cầu tiêm chủng hiệu quả, an toàn và lâu dài cho cả trẻ em lẫn người lớn. Việc triển khai vắc xin MenQuadfi tại Trung tâm Tiêm chủng Long Châu không chỉ đáp ứng tiêu chí an toàn và hiệu quả lâu dài, mà còn đánh dấu bước tiến quan trọng trong chiến lược bảo vệ sức khỏe cộng đồng, đặc biệt cho cả trẻ em và người lớn tại Việt Nam.\nXem thêm:',
 'url': 'https://tiemchunglongchau.com.vn/kien-thuc-tiem-chung/1-mui-tiem-vac-xin-menactra-gia-bao-nhieu',
 'title': '1 mũi tiêm vắc xin Menactra giá bao nhiêu tiền?'}

In [91]:
all_vi_title = [t.get("title") for t in vi_sentences if t.get("title") != "Trang chủ"]

In [88]:
homepage_docs = [t for t in vi_sentences if t.get("title") == "Trang chủ"]

In [89]:
homepage_docs

[{'text': 'Thầy Thuốc Việt Nam\nTrang cộng đồng\nTrang bác sĩ\nHotline\n0384371974\nY học cơ sở\nY học lâm sàng\nPhác đồ\nVideo\nThuốc và biệt dược\nTạp chí\nThông tin hữu ích\nĐK thành viên\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nMenu\nĐóng\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nTrang bác sĩ\nBài viết nổi bật\nĐọc nhiều nhất\nBài viết mới nhất\nDA LIỄU\n10 cách trị mụn trứng cá ở tuổi dậy thì an toàn và hiệu quả\n02/04/2023\nDINH DƯỠNG\n10 loại thực phẩm tốt cho tim mạch\n14/02/2023\nTIÊU HÓA\n10+ cách trị táo bón cho người lớn đơn giản, mau khỏi\n14/03/2023\nDA LIỄU\n12 cách chữa viêm da cơ địa tại nhà hiệu quả, an toàn, tiết kiệm\n19/03/2023\nTHẦN KINH\n12 mẹo cải thiện trí nhớ cho người hay quên!\n15/03/2023\nDA LIỄU\n13 Cách trị mụn tại nhà từ thiên nhiên hiệu quả chỉ sau 1 tuần thực hiện\n27/03/2023\nDINH DƯỠNG\n5 Bí quyết để có sức khỏe tốt trong mùa thi\n16/05/2023\nTIÊU HÓA\n7 cách chữa viêm đại tràng tại nhà\n08/03/2023\nTHUỐC VÀ DƯỢC LIỆU\n8 công dụng chữa bệnh tuyệt vời từ cây ngải cứu\n14/02/2023\nDINH DƯỠNG\nDinh dưỡng từ đậu nành giúp cải thiện bệnh mỡ máu\n03/02/2023\nDA LIỄU\nPhương pháp trị mụn trứng cá theo phác đồ của ngành da liễu hiện nay\n03/02/2023\nGAN MẬT\nCây chó đẻ răng cưa và những tác dụng tuyệt vời\n14/02/2023\nTHUỐC VÀ DƯỢC LIỆU\nĐông trùng hạ thảo có tác dụng gì?\n13/03/2023\nTHUỐC VÀ DƯỢC LIỆU\nCây Kim ngân hoa – vị thuốc quý trong Đông y\n03/02/2023\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\n11/09/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\n18/05/2026\nChia sẻ trực tuyến\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\n23/04/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\n30/12/2025\nNỘI TIẾT - CHUYỂN HÓA\nHiểu đúng về tuyến giáp: Nhận biết sớm để sống khỏe hơn\n24/12/2025\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\n22/10/2025\nVideo nổi bật\nXem tất cả\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\nVideo\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\nGiải pháp bảo vệ kép Tim Thận trên bệnh nhân Đái Tháo Đường Type 2 kèm Rối Loạn Mỡ Máu FINAL\nChia sẽ trực tuyến: Tăng huyết áp: Tầm soát sớm – Điều trị đúng – Sống khỏe mạnh\nChuyên Khoa\nXem tất cả\nTIM MẠCH\nHÔ HẤP\nTIÊU HÓA\nGAN MẬT\nNỘI TIẾT - CHUYỂN HÓA\nTHẬN - TIẾT NIỆU\nCƠ XƯƠNG KHỚP\nTHẦN KINH\nDA LIỄU\nTAI MŨI HỌNG\nBỆNH VỀ MẮT\nRĂNG HÀM MẶT\nSẢN PHỤ KHOA\nNHI KHOA\nLÃO KHOA\nUNG THƯ - UNG BƯỚU\nBỆNH TRUYỀN NHIỄM\nDINH DƯỠNG\nLỐI SỐNG LÀNH MẠNH\nTHUỐC VÀ DƯỢC LIỆU\nLÀM ĐẸP\nSƠ CỨU - CẤP CỨU\nNGỘ ĐỘC\nBỆNH VỀ MÁU\nXem tất cả\nVideo ngắn nổi bật\nXem tất cả\nVideo\nMỡ máu đã ổn, có thể ngừng thuốc không?\nVideo\nMỡ máu đã ổn định, có thể ngừng thuốc và chỉ duy trì lối sống?\nVideo\nMục tiêu điều trị mỡ máu của tôi là như thế nào?\nVideo\nMỡ máu tốt và mỡ máu xấu là gì? Hậu quả nguy hiểm khi rối loạn mỡ máu không được kiểm soát\nVideo\nNgười gầy, trông khỏe mạnh có thể bị rối loạn mỡ máu không?\nVideo\nLưu ý gì khi bổ sung đạm ở người bệnh thận mạn?\nVideo\nChức năng thận đã ổn thì có dừng hay giảm thuốc được không?\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh thận mạn?\nVideo\nGiải pháp điều trị bệnh thận mạn: Xưa và nay\nVideo\nBệnh thận mạn có thể điều trị hết không?\nVideo\nBệnh thận mạn giai đoạn mấy thì phải chạy thận?\nVideo\n6 dấu hiệu cảnh báo bệnh thận mạn cần đi khám sớm\nVideo\nĐường huyết đã ổn định, có thể giảm hoặc ngừng thuốc đái tháo đường không?\nVideo\nĂn ngon, ăn ngọt mà vẫn không sợ đường huyết?\nVideo\nTụt đường huyết có nguy hiểm không? Cách nhận biết và xử trí đúng\nVideo\nUống thuốc thế nào cho đúng? Thời điểm uống và cách xử trí khi quên liều\nVideo\nCó phải thuốc đái tháo đường nào cùng hoạt chất cũng giống nhau?\nVideo\nTuân thủ điều trị – Chìa khóa sống vui, sống khỏe\nVideo\nTrông khỏe mạnh vẫn có thể mắc đái tháo đường?\nVideo\nNhững chỉ số xét nghiệm nào giúp đánh giá bệnh đái tháo đường?\nVideo\nƯu – nhược điểm của các giải pháp điều trị đái tháo đường hiện nay\nVideo\nĐiều trị đái tháo đường không chỉ là kiểm soát đường huyết\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh đái tháo đường',
  'url': 'https://thaythuocvietnam.vn/10-cong-thuc-lam-trang-da-bang-sua-chua-khong-duong/',
  'title': 'Trang chủ'},
 {'text': 'Thầy Thuốc Việt Nam\nTrang cộng đồng\nTrang bác sĩ\nHotline\n0384371974\nY học cơ sở\nY học lâm sàng\nPhác đồ\nVideo\nThuốc và biệt dược\nTạp chí\nThông tin hữu ích\nĐK thành viên\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nMenu\nĐóng\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nTrang bác sĩ\nBài viết nổi bật\nĐọc nhiều nhất\nBài viết mới nhất\nDA LIỄU\n10 cách trị mụn trứng cá ở tuổi dậy thì an toàn và hiệu quả\n02/04/2023\nDINH DƯỠNG\n10 loại thực phẩm tốt cho tim mạch\n14/02/2023\nTIÊU HÓA\n10+ cách trị táo bón cho người lớn đơn giản, mau khỏi\n14/03/2023\nDA LIỄU\n12 cách chữa viêm da cơ địa tại nhà hiệu quả, an toàn, tiết kiệm\n19/03/2023\nTHẦN KINH\n12 mẹo cải thiện trí nhớ cho người hay quên!\n15/03/2023\nDA LIỄU\n13 Cách trị mụn tại nhà từ thiên nhiên hiệu quả chỉ sau 1 tuần thực hiện\n27/03/2023\nDINH DƯỠNG\n5 Bí quyết để có sức khỏe tốt trong mùa thi\n16/05/2023\nTIÊU HÓA\n7 cách chữa viêm đại tràng tại nhà\n08/03/2023\nTHUỐC VÀ DƯỢC LIỆU\n8 công dụng chữa bệnh tuyệt vời từ cây ngải cứu\n14/02/2023\nDINH DƯỠNG\nDinh dưỡng từ đậu nành giúp cải thiện bệnh mỡ máu\n03/02/2023\nDA LIỄU\nPhương pháp trị mụn trứng cá theo phác đồ của ngành da liễu hiện nay\n03/02/2023\nGAN MẬT\nCây chó đẻ răng cưa và những tác dụng tuyệt vời\n14/02/2023\nTHUỐC VÀ DƯỢC LIỆU\nĐông trùng hạ thảo có tác dụng gì?\n13/03/2023\nTHUỐC VÀ DƯỢC LIỆU\nCây Kim ngân hoa – vị thuốc quý trong Đông y\n03/02/2023\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\n11/09/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\n18/05/2026\nChia sẻ trực tuyến\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\n23/04/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\n30/12/2025\nNỘI TIẾT - CHUYỂN HÓA\nHiểu đúng về tuyến giáp: Nhận biết sớm để sống khỏe hơn\n24/12/2025\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\n22/10/2025\nVideo nổi bật\nXem tất cả\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\nVideo\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\nGiải pháp bảo vệ kép Tim Thận trên bệnh nhân Đái Tháo Đường Type 2 kèm Rối Loạn Mỡ Máu FINAL\nChia sẽ trực tuyến: Tăng huyết áp: Tầm soát sớm – Điều trị đúng – Sống khỏe mạnh\nChuyên Khoa\nXem tất cả\nTIM MẠCH\nHÔ HẤP\nTIÊU HÓA\nGAN MẬT\nNỘI TIẾT - CHUYỂN HÓA\nTHẬN - TIẾT NIỆU\nCƠ XƯƠNG KHỚP\nTHẦN KINH\nDA LIỄU\nTAI MŨI HỌNG\nBỆNH VỀ MẮT\nRĂNG HÀM MẶT\nSẢN PHỤ KHOA\nNHI KHOA\nLÃO KHOA\nUNG THƯ - UNG BƯỚU\nBỆNH TRUYỀN NHIỄM\nDINH DƯỠNG\nLỐI SỐNG LÀNH MẠNH\nTHUỐC VÀ DƯỢC LIỆU\nLÀM ĐẸP\nSƠ CỨU - CẤP CỨU\nNGỘ ĐỘC\nBỆNH VỀ MÁU\nXem tất cả\nVideo ngắn nổi bật\nXem tất cả\nVideo\nMỡ máu đã ổn, có thể ngừng thuốc không?\nVideo\nMỡ máu đã ổn định, có thể ngừng thuốc và chỉ duy trì lối sống?\nVideo\nMục tiêu điều trị mỡ máu của tôi là như thế nào?\nVideo\nMỡ máu tốt và mỡ máu xấu là gì? Hậu quả nguy hiểm khi rối loạn mỡ máu không được kiểm soát\nVideo\nNgười gầy, trông khỏe mạnh có thể bị rối loạn mỡ máu không?\nVideo\nLưu ý gì khi bổ sung đạm ở người bệnh thận mạn?\nVideo\nChức năng thận đã ổn thì có dừng hay giảm thuốc được không?\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh thận mạn?\nVideo\nGiải pháp điều trị bệnh thận mạn: Xưa và nay\nVideo\nBệnh thận mạn có thể điều trị hết không?\nVideo\nBệnh thận mạn giai đoạn mấy thì phải chạy thận?\nVideo\n6 dấu hiệu cảnh báo bệnh thận mạn cần đi khám sớm\nVideo\nĐường huyết đã ổn định, có thể giảm hoặc ngừng thuốc đái tháo đường không?\nVideo\nĂn ngon, ăn ngọt mà vẫn không sợ đường huyết?\nVideo\nTụt đường huyết có nguy hiểm không? Cách nhận biết và xử trí đúng\nVideo\nUống thuốc thế nào cho đúng? Thời điểm uống và cách xử trí khi quên liều\nVideo\nCó phải thuốc đái tháo đường nào cùng hoạt chất cũng giống nhau?\nVideo\nTuân thủ điều trị – Chìa khóa sống vui, sống khỏe\nVideo\nTrông khỏe mạnh vẫn có thể mắc đái tháo đường?\nVideo\nNhững chỉ số xét nghiệm nào giúp đánh giá bệnh đái tháo đường?\nVideo\nƯu – nhược điểm của các giải pháp điều trị đái tháo đường hiện nay\nVideo\nĐiều trị đái tháo đường không chỉ là kiểm soát đường huyết\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh đái tháo đường',
  'url': 'https://thaythuocvietnam.vn/10-kha-nang-sieu-viet-cua-co-nguoi/',
  'title': 'Trang chủ'},
 {'text': 'Thầy Thuốc Việt Nam\nTrang cộng đồng\nTrang bác sĩ\nHotline\n0384371974\nY học cơ sở\nY học lâm sàng\nPhác đồ\nVideo\nThuốc và biệt dược\nTạp chí\nThông tin hữu ích\nĐK thành viên\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nMenu\nĐóng\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nTrang bác sĩ\nBài viết nổi bật\nĐọc nhiều nhất\nBài viết mới nhất\nDA LIỄU\n10 cách trị mụn trứng cá ở tuổi dậy thì an toàn và hiệu quả\n02/04/2023\nDINH DƯỠNG\n10 loại thực phẩm tốt cho tim mạch\n14/02/2023\nTIÊU HÓA\n10+ cách trị táo bón cho người lớn đơn giản, mau khỏi\n14/03/2023\nDA LIỄU\n12 cách chữa viêm da cơ địa tại nhà hiệu quả, an toàn, tiết kiệm\n19/03/2023\nTHẦN KINH\n12 mẹo cải thiện trí nhớ cho người hay quên!\n15/03/2023\nDA LIỄU\n13 Cách trị mụn tại nhà từ thiên nhiên hiệu quả chỉ sau 1 tuần thực hiện\n27/03/2023\nDINH DƯỠNG\n5 Bí quyết để có sức khỏe tốt trong mùa thi\n16/05/2023\nTIÊU HÓA\n7 cách chữa viêm đại tràng tại nhà\n08/03/2023\nTHUỐC VÀ DƯỢC LIỆU\n8 công dụng chữa bệnh tuyệt vời từ cây ngải cứu\n14/02/2023\nDINH DƯỠNG\nDinh dưỡng từ đậu nành giúp cải thiện bệnh mỡ máu\n03/02/2023\nDA LIỄU\nPhương pháp trị mụn trứng cá theo phác đồ của ngành da liễu hiện nay\n03/02/2023\nGAN MẬT\nCây chó đẻ răng cưa và những tác dụng tuyệt vời\n14/02/2023\nTHUỐC VÀ DƯỢC LIỆU\nĐông trùng hạ thảo có tác dụng gì?\n13/03/2023\nTHUỐC VÀ DƯỢC LIỆU\nCây Kim ngân hoa – vị thuốc quý trong Đông y\n03/02/2023\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\n11/09/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\n18/05/2026\nChia sẻ trực tuyến\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\n23/04/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\n30/12/2025\nNỘI TIẾT - CHUYỂN HÓA\nHiểu đúng về tuyến giáp: Nhận biết sớm để sống khỏe hơn\n24/12/2025\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\n22/10/2025\nVideo nổi bật\nXem tất cả\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\nVideo\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\nGiải pháp bảo vệ kép Tim Thận trên bệnh nhân Đái Tháo Đường Type 2 kèm Rối Loạn Mỡ Máu FINAL\nChia sẽ trực tuyến: Tăng huyết áp: Tầm soát sớm – Điều trị đúng – Sống khỏe mạnh\nChuyên Khoa\nXem tất cả\nTIM MẠCH\nHÔ HẤP\nTIÊU HÓA\nGAN MẬT\nNỘI TIẾT - CHUYỂN HÓA\nTHẬN - TIẾT NIỆU\nCƠ XƯƠNG KHỚP\nTHẦN KINH\nDA LIỄU\nTAI MŨI HỌNG\nBỆNH VỀ MẮT\nRĂNG HÀM MẶT\nSẢN PHỤ KHOA\nNHI KHOA\nLÃO KHOA\nUNG THƯ - UNG BƯỚU\nBỆNH TRUYỀN NHIỄM\nDINH DƯỠNG\nLỐI SỐNG LÀNH MẠNH\nTHUỐC VÀ DƯỢC LIỆU\nLÀM ĐẸP\nSƠ CỨU - CẤP CỨU\nNGỘ ĐỘC\nBỆNH VỀ MÁU\nXem tất cả\nVideo ngắn nổi bật\nXem tất cả\nVideo\nMỡ máu đã ổn, có thể ngừng thuốc không?\nVideo\nMỡ máu đã ổn định, có thể ngừng thuốc và chỉ duy trì lối sống?\nVideo\nMục tiêu điều trị mỡ máu của tôi là như thế nào?\nVideo\nMỡ máu tốt và mỡ máu xấu là gì? Hậu quả nguy hiểm khi rối loạn mỡ máu không được kiểm soát\nVideo\nNgười gầy, trông khỏe mạnh có thể bị rối loạn mỡ máu không?\nVideo\nLưu ý gì khi bổ sung đạm ở người bệnh thận mạn?\nVideo\nChức năng thận đã ổn thì có dừng hay giảm thuốc được không?\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh thận mạn?\nVideo\nGiải pháp điều trị bệnh thận mạn: Xưa và nay\nVideo\nBệnh thận mạn có thể điều trị hết không?\nVideo\nBệnh thận mạn giai đoạn mấy thì phải chạy thận?\nVideo\n6 dấu hiệu cảnh báo bệnh thận mạn cần đi khám sớm\nVideo\nĐường huyết đã ổn định, có thể giảm hoặc ngừng thuốc đái tháo đường không?\nVideo\nĂn ngon, ăn ngọt mà vẫn không sợ đường huyết?\nVideo\nTụt đường huyết có nguy hiểm không? Cách nhận biết và xử trí đúng\nVideo\nUống thuốc thế nào cho đúng? Thời điểm uống và cách xử trí khi quên liều\nVideo\nCó phải thuốc đái tháo đường nào cùng hoạt chất cũng giống nhau?\nVideo\nTuân thủ điều trị – Chìa khóa sống vui, sống khỏe\nVideo\nTrông khỏe mạnh vẫn có thể mắc đái tháo đường?\nVideo\nNhững chỉ số xét nghiệm nào giúp đánh giá bệnh đái tháo đường?\nVideo\nƯu – nhược điểm của các giải pháp điều trị đái tháo đường hiện nay\nVideo\nĐiều trị đái tháo đường không chỉ là kiểm soát đường huyết\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh đái tháo đường',
  'url': 'https://thaythuocvietnam.vn/10-nguyen-nhan-gay-rong-kinh-chi-em-phu-nu-can-biet/',
  'title': 'Trang chủ'},
 {'text': 'Thầy Thuốc Việt Nam\nTrang cộng đồng\nTrang bác sĩ\nHotline\n0384371974\nY học cơ sở\nY học lâm sàng\nPhác đồ\nVideo\nThuốc và biệt dược\nTạp chí\nThông tin hữu ích\nĐK thành viên\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nMenu\nĐóng\nTrang chủ\nGiới thiệu\nBệnh thường gặp\nVideo sức khỏe ngắn\nChia sẻ trực tuyến\nKhám bệnh Online\nLiên hệ hợp tác\nTrang bác sĩ\nBài viết nổi bật\nĐọc nhiều nhất\nBài viết mới nhất\nDA LIỄU\n10 cách trị mụn trứng cá ở tuổi dậy thì an toàn và hiệu quả\n02/04/2023\nDINH DƯỠNG\n10 loại thực phẩm tốt cho tim mạch\n14/02/2023\nTIÊU HÓA\n10+ cách trị táo bón cho người lớn đơn giản, mau khỏi\n14/03/2023\nDA LIỄU\n12 cách chữa viêm da cơ địa tại nhà hiệu quả, an toàn, tiết kiệm\n19/03/2023\nTHẦN KINH\n12 mẹo cải thiện trí nhớ cho người hay quên!\n15/03/2023\nDA LIỄU\n13 Cách trị mụn tại nhà từ thiên nhiên hiệu quả chỉ sau 1 tuần thực hiện\n27/03/2023\nDINH DƯỠNG\n5 Bí quyết để có sức khỏe tốt trong mùa thi\n16/05/2023\nTIÊU HÓA\n7 cách chữa viêm đại tràng tại nhà\n08/03/2023\nTHUỐC VÀ DƯỢC LIỆU\n8 công dụng chữa bệnh tuyệt vời từ cây ngải cứu\n14/02/2023\nDINH DƯỠNG\nDinh dưỡng từ đậu nành giúp cải thiện bệnh mỡ máu\n03/02/2023\nDA LIỄU\nPhương pháp trị mụn trứng cá theo phác đồ của ngành da liễu hiện nay\n03/02/2023\nGAN MẬT\nCây chó đẻ răng cưa và những tác dụng tuyệt vời\n14/02/2023\nTHUỐC VÀ DƯỢC LIỆU\nĐông trùng hạ thảo có tác dụng gì?\n13/03/2023\nTHUỐC VÀ DƯỢC LIỆU\nCây Kim ngân hoa – vị thuốc quý trong Đông y\n03/02/2023\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\n11/09/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\n18/05/2026\nChia sẻ trực tuyến\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\n23/04/2026\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\n30/12/2025\nNỘI TIẾT - CHUYỂN HÓA\nHiểu đúng về tuyến giáp: Nhận biết sớm để sống khỏe hơn\n24/12/2025\nChia sẻ trực tuyến\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\n22/10/2025\nVideo nổi bật\nXem tất cả\nCHIA SẺ TRỰC TUYẾN: ĐỪNG CHỜ BIẾN CỐ – HÃY KIỂM SOÁT MỠ MÁU NGAY HÔM NAY\nVideo\nĐÁI THÁO ĐƯỜNG: TUÂN THỦ ĐIỀU TRỊ – AN VUI SUM VẦY\nCHIA SẺ TRỰC TUYẾN: THẬN KHỎE – TÂM YÊN, AN NHIÊN ĐÓN TẾT\nCHIA SẺ TRỰC TUYẾN: CHÌA KHÓA MỚI BẢO VỆ TIM THẬN TRÊN BỆNH NHÂN ĐÁI THẢO ĐƯỜNG KÈM RỐI LOẠN MỠ MÁU\nCHIA SẺ TRỰC TUYẾN: GIẢI PHÁP MỚI BẢO VỆ KÉP TIM – THẬN TRÊN BỆNH NHÂN ĐÁI THÁO ĐƯỜNG TUÝP 2\nGiải pháp bảo vệ kép Tim Thận trên bệnh nhân Đái Tháo Đường Type 2 kèm Rối Loạn Mỡ Máu FINAL\nChia sẽ trực tuyến: Tăng huyết áp: Tầm soát sớm – Điều trị đúng – Sống khỏe mạnh\nChuyên Khoa\nXem tất cả\nTIM MẠCH\nHÔ HẤP\nTIÊU HÓA\nGAN MẬT\nNỘI TIẾT - CHUYỂN HÓA\nTHẬN - TIẾT NIỆU\nCƠ XƯƠNG KHỚP\nTHẦN KINH\nDA LIỄU\nTAI MŨI HỌNG\nBỆNH VỀ MẮT\nRĂNG HÀM MẶT\nSẢN PHỤ KHOA\nNHI KHOA\nLÃO KHOA\nUNG THƯ - UNG BƯỚU\nBỆNH TRUYỀN NHIỄM\nDINH DƯỠNG\nLỐI SỐNG LÀNH MẠNH\nTHUỐC VÀ DƯỢC LIỆU\nLÀM ĐẸP\nSƠ CỨU - CẤP CỨU\nNGỘ ĐỘC\nBỆNH VỀ MÁU\nXem tất cả\nVideo ngắn nổi bật\nXem tất cả\nVideo\nMỡ máu đã ổn, có thể ngừng thuốc không?\nVideo\nMỡ máu đã ổn định, có thể ngừng thuốc và chỉ duy trì lối sống?\nVideo\nMục tiêu điều trị mỡ máu của tôi là như thế nào?\nVideo\nMỡ máu tốt và mỡ máu xấu là gì? Hậu quả nguy hiểm khi rối loạn mỡ máu không được kiểm soát\nVideo\nNgười gầy, trông khỏe mạnh có thể bị rối loạn mỡ máu không?\nVideo\nLưu ý gì khi bổ sung đạm ở người bệnh thận mạn?\nVideo\nChức năng thận đã ổn thì có dừng hay giảm thuốc được không?\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh thận mạn?\nVideo\nGiải pháp điều trị bệnh thận mạn: Xưa và nay\nVideo\nBệnh thận mạn có thể điều trị hết không?\nVideo\nBệnh thận mạn giai đoạn mấy thì phải chạy thận?\nVideo\n6 dấu hiệu cảnh báo bệnh thận mạn cần đi khám sớm\nVideo\nĐường huyết đã ổn định, có thể giảm hoặc ngừng thuốc đái tháo đường không?\nVideo\nĂn ngon, ăn ngọt mà vẫn không sợ đường huyết?\nVideo\nTụt đường huyết có nguy hiểm không? Cách nhận biết và xử trí đúng\nVideo\nUống thuốc thế nào cho đúng? Thời điểm uống và cách xử trí khi quên liều\nVideo\nCó phải thuốc đái tháo đường nào cùng hoạt chất cũng giống nhau?\nVideo\nTuân thủ điều trị – Chìa khóa sống vui, sống khỏe\nVideo\nTrông khỏe mạnh vẫn có thể mắc đái tháo đường?\nVideo\nNhững chỉ số xét nghiệm nào giúp đánh giá bệnh đái tháo đường?\nVideo\nƯu – nhược điểm của các giải pháp điều trị đái tháo đường hiện nay\nVideo\nĐiều trị đái tháo đường không chỉ là kiểm soát đường huyết\nVideo\nSGLT2i – Mảnh ghép hiệu quả và chi phí trong điều trị bệnh đái tháo đường',
  'url': 'https://thaythuocvietnam.vn/10-y-bac-si-thay-nhau-hien-mau-cuu-san-phu/',
  'title': 'Trang chủ'},

In [90]:
len(homepage_docs)

2230

In [92]:
all_vi_title

['U malt dạ dày Phần 1: Tổng quan, chẩn đoán và triệu chứng',
 '0h hôm nay 26/7 công bố điểm thi THPT Quốc gia 2021 | Sức Khỏe Cộng Đồng',
 '1/2 số người nhiễm Omicron có thể không biết bản thân bị nhiễm bệnh',
 'Bà bầu bị sưng nướu răng trong cùng: Nguyên nhân, triệu chứng và cách điều trị',
 '¾ phụ huynh Anh “bỏ quên” đôi mắt của con nhỏ',
 'Béo phì • Hello Bacsi',
 '1 người chết, 18 người nhập viện sau khi ăn cỗ ở Thái Bình: Bác sĩ chỉ món khoái khẩu mang ổ bệnh',
 '“Người dân sẽ được thụ hưởng chất lượng khám chữa bệnh Quốc tế ngay tại Bệnh viện Bạch Mai”',
 'Tin vui cho người lớn tuổi bị sa sút trí tuệ',
 '1.027 mẫu liên quan đến Bệnh viện Phụ sản có kết quả xét nghiệm âm tính với vi-rút SARS-CoV-2',
 '1 mũi tiêm vắc xin Menactra giá bao nhiêu tiền?',
 '1/6 bệnh nhân mắc ung thư đều do viêm: 5 vị trí trên cơ thể bị viêm cảnh báo ung thư đang đến gần',
 'Ðảm bảo học sinh, sinh viên được chăm sóc sức khỏe toàn diện',
 "1.000 người tham gia ngày 'Toàn dân hiến máu tình nguyện'",
 '‘Ba trắng một vàng’ âm thầm gây hại thận',
 '1.000 tỷ đồng phát triển hệ thống Bệnh viện Risemount Thiện Nhân',
 '1 bác sĩ và 4 điều dưỡng ở TPHCM bị tước chứng chỉ hành nghề',
 '10 bài tập tăng chiều cao trước khi đi ngủ - YouMed News',
 'Ở khu cách ly Covid-19...',
 'Ðẹp nhờ khoai lang',
 '[Infographic]: Thông điệp 5T- "Pháo đài" chống dịch COVID-19 trong thời gian tăng cường giãn cách xã hội',
 '10 bài tập cơ bụng bạn có thể thực hiện trong khi xem Netflix trên giường',
 'Đặt thể hang nhân tạo điều trị rối loạn cương dương',
 '10 hệ thống y tế Việt Nam có mức độ nhận diện tốt nhất với người nước ngoài',
 '03 nguyên tắc cha mẹ cần biết khi cho trẻ uống Oresol | Sức khỏe Việt',
 '1.628 người hiến máu, hiến tiểu cầu trong 7 ngày nghỉ Tết - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '1.000 người dân được khám miễn phí, AI sắp hỗ trợ y tế cơ sở',
 '14 danh mục thuốc, nguyên liệu làm thuốc được xác định mã số hàng hóa',
 '100% bệnh viện công tại Khánh Hòa sử dụng bệnh án điện tử',
 '03 bệnh nhân may mắn được ghép giác mạc miễn phí tại BV. FV',
 '10 năm tim đập loạn nhịp, tôi đã ổn định được nhịp tim nhờ cách này',
 '1 ca mắc bệnh sởi lây nhiều hơn COVID-19',
 '1 học sinh mắc bạch hầu tử vong, cách ly những người tiếp xúc gần',
 '10 loại thực phẩm giúp giảm cholesterol bảo vệ tim',
 '11 nhóm người được BHYT thanh toán 100% chi phí khám chữa bệnh BHYT từ năm 2026',
 'Ăn gì để dễ thụ thai? 14 thực phẩm giúp tăng khả năng đậu thai',
 '12 học sinh tiểu học nhập viện sau khi ăn cơm nắm ngoài trường',
 '10 thực phẩm lành mạnh nhất giúp cải thiện sức khỏe toàn diện',
 'Bảo hiểm y tế toàn dân - chính sách nhân văn trong kỷ nguyên mới',
 'Theo chân người dân biên viễn miền Tây xứ Nghệ xuyên rừng hái “lộc Trời”',
 '10.000 đơn vị máu hiến kịp bổ sung cho điều trị sau Tết',
 '1 chén dâu tây mỗi ngày giúp giảm mỡ máu lại tốt cho tim, não',
 'Một chiến sĩ gặp tai nạn trên đường thực hiện nhiệm vụ chữa cháy tại KCN Thụy Vân | Sức Khỏe Cộng Đồng',
 '1 giờ cứu sống thành công trẻ sơ sinh bị ngạt trắng do sa dây rau',
 '1 lần xạ trị bao nhiêu tiền? Giải đáp thắc mắc về chi phí xạ trị',
 "PGS.TS Trần Minh Điển: 'Đắp lòng trắng trứng gà vào vết tiêm dễ gây nhiễm khuẩn huyết' | Bệnh viện Nhi Trung ương",
 'Bệnh vùi dương vật: Nguyên nhân, triệu chứng và phương pháp điều trị hiệu quả',
 '[hỏi đáp cùng bác sĩ] chỉ số bmi và bmr là gì và có thể “cảnh báo” •',
 '1,5 tỷ đồng trị liệu ung thư bằng vắc xin: Giám đốc Bệnh viện ung bướu nói gì?',
 'Khoa học phát hiện cách xác định cà phê nào có thể tốt hơn cho sức khỏe',
 '1 tuần xuống 3kg: Thuốc giảm cân nào bằng ly nước này',
 '1 ngày ăn 2 bữa có giảm cân không? Góc nhìn khoa học - Trung tâm Tiêm chủng Long Châu',
 '1.172 cán bộ, công chức làm việc tại Trung tâm Hành chính thành phố âm tính với SARS-CoV-2',
 '1.088 người nhập viện do tai nạn giao thông',
 "1 người tử vong, 4 ca cấp cứu, lời cảnh báo về món ăn 'chết người'",
 '1/5 số người tử vong trên thế giới là do thịt đỏ và nước ngọt',
 '1 bó rau diếp cá - 3 cách trị mụn, sau 7 ngày vết thâm nám tan biến',
 '“An nghỉ” trên cung trăng',
 '“Lá chắn” phòng, chống dịch bệnh',
 'Phát hiện kẹo ngậm điều trị chứng liệt dương ở nam giới chứa chất cấm',
 'Bạo lực đối với phụ nữ đã trở thành “vấn đề sức khỏe mang tính toàn cầu”',
 'Những người không nên ăn tỏi',
 '10 dấu hiệu cảnh báo cơ thể bạn đang tiêu thụ quá nhiều đường',
 '10 bài thuốc hay theo y học cổ truyền từ râu ngô | Sức khỏe Việt',
 '100% cơ sở y tế ở Cần Thơ triển khai bệnh án điện tử',
 '1 phụ nữ nguy kịch do ngộ độc thuốc gây tê nhổ răng',
 '2 hình thức hỗ trợ thuốc miễn phí cho người bệnh',
 '1 học sinh ở Phú Quốc tử vong, nghi bị mắc bệnh viêm não mô cầu',
 '14 người tại Huế nhập viện nghi ngộ độc do ăn bánh mì',
 'Trải nghiệm y tế thông minh, hiện đại tại gian triển lãm của Bộ Y tế',
 '15% dân số toàn tỉnh có hồ sơ điện tử quản lý sức khỏe',
 "10 giờ mổ cứu ca ung thư hốc mũi 'chưa từng có'",
 '10 dấu hiệu sắp có kinh nguyệt mà chị em nên biết - YouMed News',
 '4 phương pháp can thiệp ngoại khoa điều trị bệnh trĩ - Bệnh viện Việt Đức',
 '1 triệu người Nam Mỹ nhiễm bệnh Chikungunya đau nhức dữ dội',
 'Trẻ có bệnh nền, bệnh mạn tính cần cảnh giác với virus Rhino',
 '100% người dân được khám sức khỏe định kỳ vào năm 2026: Mục tiêu và thực tế còn cách xa',
 '10 loại thực phẩm và đồ uống giúp làn da sáng khỏe',
 '20 năm chờ đợi và cú "hồi sinh" nụ cười bằng kỹ thuật vi phẫu phức tạp',
 'Việt Nam quyết tâm chiến thắng đại dịch COVID-19',
 '450 cán bộ, chiến sĩ Công an tỉnh Thanh Hóa tham gia hiến máu tình nguyện',
 '12 Cần Đước đầu tư trên 30 tỷ đồng nâng cấp xây mới Trung tâm Y tế Cần Đước cơ sở II',
 'Tổng quan những điều cần biết về Bệnh viện Phạm Ngọc Thạch',
 '100% bệnh viện phải triển khai bệnh án điện tử trước tháng 10/2025 - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '10 bài tập cho thân trên nữ mà bạn nhất định phải thử',
 '1 muỗng tỏi ngâm mật ong mỗi ngày: Điều gì xảy ra với đường huyết và huyết áp?',
 '10 điều khiến bạn trở thành người béo phì • Hello Bacsi',
 'Block nhánh phải là bệnh lý gì và việc điều trị có phức tạp không?',
 '1 trường hợp tử vong sốt xuất huyết, Đắk Lắk cảnh báo nguy cơ có thêm nhiều bệnh nhân',
 "'1 lít xăng có đến hơn 5 Bộ ngành cùng quản lý' | Sức Khỏe Cộng Đồng",
 'Nghiên cứu mới: Loại chất trong cơm giúp chống 2 loại "bệnh thời đại"',
 '10 cách ngăn ngừa ung thư',
 'bí quyết làm đẹp của phụ nữ Nhật Bản, giúp bạn trẻ ra cả chục tuổi',
 '1 phút plank đốt bao nhiêu calo? Cách tập plank hiệu quả',
 '1 chiếc quần jean ống loe - 1001 cách phối đồ ngày hè cực thời thượng, trẻ trung',
 '1 phụ nữ bị rắn cạp nia cắn tử vong',
 '1.277 người được tiêm mũi 2 vaccine AstraZeneca đợt 5',
 'Ðáp ứng nhu cầu sàng lọc chẩn đoán trước sinh và sơ sinh vùng ÐBSCL',
 'Giảm cân an toàn đón Tết',
 '1.500 đại biểu dự hội nghị kiểm soát nhiễm khuẩn, khu vực châu Á',
 'Một trường hợp tử vong do sốt xuất huyết',
 '10 loại thực phẩm giúp xương chắc khỏe, phòng ngừa loãng xương hiệu quả',
 '1.000 người đi bộ đồng hành nâng cao nhận thức cộng đồng về bệnh đột quỵ',
 '1 sản phẩm chăm sóc da bị thu hồi do công thức không đúng hồ sơ công bố',
 '19 người nghi ngộ độc sau khi ăn bánh mì tại Đồng Tháp',
 '10 bí quyết làm đẹp tự nhiên cho phái nữ | Sức khỏe Việt',
 '“Nguyện đem hết khả năng để phục vụ, chăm sóc và hoàn thiện nét đẹp Việt”',
 'Những sai lầm khiến bạn đang phá hủy giấc ngủ của mình',
 'Đại biểu Quốc hội lo ngại về nguy cơ độc quyền thuốc trên thị trường',
 '10 khuyến cáo của chuyên gia để bảo vệ tim mạch cho người cao tuổi',
 '1 triệu liều vắc xin Moderna do Mỹ trao tặng về đến Hà Nội',
 '10 lợi ích không ngờ của yoga đối với sức khỏe - YouMed News',
 '10 điểm mới của chương trình phòng, chống COVID-19',
 '2 trẻ tử vong sau tiêm vaccine không liên quan đến vaccine và thực hành tiêm chủng',
 'Cách nấu nước dashi rau củ cho bé 5 tháng tuổi',
 '3 bệnh nhân tử vong do ăn phải nấm độc',
 '3 trường hợp trẻ nhập viện trong tình trạng nguy kịch do bị ong đốt | Bệnh viện Nhi Trung ương',
 '10 món ăn nhẹ buổi tối giúp ngủ ngon hơn',
 '194 học sinh thi chọn đội tuyển Olympic quốc tế và khu vực',
 '75 năm Việt Nam đồng hành cùng Tổ chức Y tế thế giới',
 '20 bệnh nền có nguy cơ gia tăng mức độ nặng khi mắc COVID-19',
 '12 ca ghép giác mạc thành công bằng nguồn mô hiến tặng từ Nepal - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '6 nguyên nhân thường gặp gây đau hậu môn - Bệnh viện Việt Đức',
 '4 ngày duy nhất - khám sức khỏe tại nhà chỉ 760.000 đồng cùng MEDLATEC',
 '10 người ngộ độc sau bữa ăn Tết với trứng cá sấu hỏa tiễn',
 'Đổi mới cơ chế tự chủ tài chính, nâng cao hiệu quả hoạt động',
 '10 biện pháp khắc phục tại nhà để có làn da tươi sáng, căng bóng',
 'Các loại thuốc trị chấy rận phổ biến và lưu ý khi dùng',
 'Thực đơn cho người béo phì giảm cân lành mạnh • Hello Bacsi',
 '1 người chết, 12 người nhập viện sau khi ăn giỗ',
 'Mưa lũ ở Điện Biên làm 2 mẹ con tử vong',
 '1 ngày 4 trẻ sơ sinh tử vong tại Bệnh viện Sản Nhi tỉnh Bắc Ninh | Sức Khỏe Cộng Đồng',
 '10 lưu ý của bệnh nhân chạy thận nhân tạo trong mùa Covid-19',
 'Sắp thử nghiệm thuốc ung thư do AI thiết kế trên người',
 '1 tuần nên uống bao nhiêu viên C sủi? Hướng dẫn sử dụng an toàn - Trung tâm Tiêm chủng Long Châu',
 '10 biểu hiện nguy hiểm và 5 nguyên tắc phòng bệnh trẻ sốt siêu vi',
 '10 cách dùng hoa đu đủ đực cho mọi nhà',
 '1.360 người nhập cảnh từ ngày 8.3',
 '10 bài thuốc chữa bệnh từ cây nhọ nồi',
 '1 củ khoai tây - 3 cách xóa mờ đốm đen, điều trị tận gốc mụn và loại bỏ hoàn toàn khuyết điểm giúp da đẹp không tì vết',
 'Ðậu phộng rang ít muối giúp giảm cân, hạ huyết áp hiệu quả',
 '10,3 tỷ đồng phòng và trị liệu rối nhiễu tâm trí cho người tâm thần',
 'Bác sĩ Bệnh viện HN Việt Đức cảnh báo bệnh lý khớp giả xương thuyền - Bệnh viện Việt Đức',
 '10 thực phẩm cho người cao huyết áp mà có thể bạn chưa biết - YouMed News',
 '“Thời gian vàng” trong cấp cứu đột quỵ',
 '10 công dụng chữa bệnh từ cây bí đỏ | Sức khỏe Việt',
 'Phòng tránh dịch nơi cộng cộng: Chớ thấy bình an mà chủ quan',
 'Những loại rau củ có tính kháng viêm cao',
 '10 loại trái cây giúp bổ sung protein tự nhiên, tốt cho tim và tiêu hóa',
 'Những hữu ích của quả quất đối với sức khỏe',
 '11 người ở Bắc Kạn ngộ độc củ ấu tẩu',
 '3 nguyên nhân chính làm gia tăng các bệnh không lây nhiễm',
 '2 sản phẩm thực phẩm bảo vệ sức khỏe có chất cấm Sibutramine',
 '1000 ngày vàng - chìa khóa cho chiều cao, trí tuệ và miễn dịch vượt trội',
 'Bệnh viện Quân y 87 chung tay cùng nhân dân vùng lũ',
 '10 thực phẩm lành mạnh nhất giúp cải thiện sức khỏe toàn diện',
 "2 ca ghép tạng xuyên đêm giành lại sự sống từ 'tử thần'",
 '22 đường dây nóng tiếp nhận thông tin về dịch bệnh do virus corona',
 '2.320 người được xét nghiệm sàng lọc lao miễn phí - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '100% bệnh viện TP.HCM phải nghiêm túc tham gia hệ thống tiếp nhận và phản ánh của người dân',
 '10 hoạt động nổi bật của Bệnh viện Nhi Đồng 1 năm 2010',
 'Hơn 11,6 nghìn tỷ đồng được huy động vào Quỹ vaccine phòng Covid-19',
 'Bác sĩ cảnh báo vì sao nên cẩn trọng khi sử dụng nước giếng để nấu ăn',
 "3 loại rau dễ tìm là 'thần dược' cho thận yếu",
 '8 nguyên tắc “vàng” uống rượu bia an toàn trong dịp Tết',
 '10 cách để tăng cường khả năng sinh sản của nam giới và tăng số lượng tinh trùng',
 'Các vị trí đau đầu nguy hiểm và cách xử lý',
 '3 nạn nhân của vụ cháy nhà trọ ở Trung Kính đã chuyển sang Bệnh viện Bạch Mai điều trị',
 'Chiều dài phôi thai 7 tuần tuổi là bao nhiêu?',
 '10 thực phẩm ăn không đúng cách sẽ mất chất dinh dưỡng • Hello Bacsi',
 '1 người tử vong, 11 người nhập viện ở vùng nghi là ổ dịch bạch hầu',
 '5 nguyên tắc "bỏ túi" cha mẹ cần biết khi đưa trẻ đi khám bệnh',
 "1 sản phụ 'đẻ rớt' trên xe grab khi đang trên đường tới bệnh viện | Sức Khỏe Cộng Đồng",
 'Bộ Công an khởi tố, khám xét nhà Viện trưởng Viện Y dược học dân tộc TPHCM',
 '100 ca sản phụ có thai mắc sốt xuất huyết đã được điều trị an toàn',
 '1 giờ nhìn chằm chằm vào màn hình làm tăng 20% nguy cơ cận thị',
 '10 cách giảm đau lưng cho bà bầu được nhiều mẹ áp dụng',
 '10 cách diện quần short trẻ trung và tinh tế, phù hợp với phụ nữ U40',
 '10 ca tử vong khi sốt xuất huyết bùng phát, TPHCM khuyến khích dân tiêm vắc xin',
 '1.492 mẫu xét nghiệm của công nhân tại Cẩm Giàng âm tính với SARS-CoV-2.',
 '10 bí kíp chăm sóc da hằng ngày',
 '0h00 ngày 26/6, Hà Nội cho phép người dân tham gia hoạt động thể thao ngoài trời',
 '10 cách hiệu quả để làm cho khuôn mặt trông trẻ lại một lần nữa',
 'Ðẩy mạnh truyền thông về HIV đến công nhân, người lao động',
 'Bác sĩ Nhi chỉ rõ 3 bệnh giao mùa trẻ em hay gặp phải, cha mẹ cần lưu ý - Bệnh viện Việt Đức',
 'Nhiều cấp ngành cùng hành động',
 '11 lợi ích của vitamin C cho làn da và cách sử dụng - YouMed News',
 'Vắcxin Sputnik V của Nga nhận được sự ủng hộ từ nhiều nước Tây Âu',
 '10 phương pháp bảo vệ sức khỏe trong mùa bão lụt và mưa lũ',
 '10 loại thảo dược giúp tăng cường sức khỏe và làm đẹp | Sức khỏe Việt',
 'Nam giới bị thận hư nên ăn gì?',
 'Bệnh viện Quân y 105: Năm 2023 hoàn thành vượt mức các chỉ tiêu chuyên',
 '112 cá nhân ngành Y tế Hà Nội được trao tặng danh hiệu “Người tốt, việc tốt” năm 2024',
 '236 ca tử vong, gần 29.000 người nhập viện trong ngày đầu nghỉ lễ',
 '3 ngày nghỉ Tết đầu tiên, các cơ sở y tế khám, cấp cứu cho 728.836 bệnh nhân - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '12 giờ căng thẳng nối 2 bàn tay bị chém gần đứt lìa',
 '3 bệnh viện tại Quảng Ninh được xếp cấp chuyên sâu',
 '12 loại rau củ nên ăn thường xuyên để sống khỏe và kéo dài tuổi thọ',
 '31 tỉnh, thành ký kết xây dựng mạng lưới phòng chống ung thư',
 '11 thực phẩm giàu sắt nên bổ sung vào chế độ ăn cho người thiếu máu do thiếu sắt',
 '67% trẻ tăng động giảm chú ý có kèm những rối loạn đồng diễn',
 '34 du khách ngộ độc thực phẩm, Đà Nẵng kiểm tra 2 hàng hàng',
 'Bác sỹ BV Việt Đức lần đầu phẫu thuật phối hợp hai đường mổ, loại bỏ khối u não',
 '10 mẹo nhỏ để không bị tăng cân sau Tết',
 '"Tôi gọi đó là tình yêu"',
 '3 tách cà phê mỗi ngày: Phát hiện tác dụng bất ngờ với gan',
 'Ăn mặn có gây tổn thương thận?',
 'Củ đậu kỵ với gì? những kiến thức giúp bạn tận dụng lợi ích tuyệt vời từ củ đậu',
 '10 cách thú vị để dạy trẻ về giá trị của tiền bạc',
 '1 tuần nên ngâm chân mấy lần, 5 lưu ý khi ngâm chân?',
 'Chạy bộ như thế nào để không bị to chân và cách giúp chân thon gọn',
 '1 tỉ người bị rối loạn thần kinh',
 '1 tỉnh cho nghỉ học vì có hơn 300 F0 là học sinh và giáo viên | Sức Khỏe Cộng Đồng',
 '15 thực phẩm tăng sức đề kháng trong mùa hè bạn nên thêm vào thực •',
 '10 cách mặc chân váy giúp phong cách đi du lịch nổi bật hơn',
 '10 sự thực đáng ngạc nhiên về “chuyện ấy” ở phái đẹp',
 '1.510 cơ sở vi phạm về an toàn thực phẩm',
 '1 lọ oxy già - 1001 tác dụng làm đẹp chẳng khác gì mỹ phẩm hàng hiệu',
 '10 biện pháp giúp giảm nguy cơ ung thư vú',
 '10 dấu hiệu bệnh gout thường gặp không thể chủ quan',
 '10 dấu hiệu cảnh báo không nên bỏ qua về bệnh ung thư đại tràng',
 '1 triệu liều vaccine của UAE đã về đến Việt Nam',
 '“Bao cao su” cho... USB',
 '10 dấu hiệu cảnh báo căn bệnh ung thư rất phổ biến tại Việt Nam',
 'Báo động chất lượng tinh trùng của quý ông giảm sốc nghiêm trọng vì thói quen không ngờ - Bệnh viện Việt Đức',
 "'1 hôi, 2 to, 2 nhỏ' cảnh báo đàn ông bị mãn kinh, suy giảm sức khỏe",
 'Hỗ trợ Bệnh viện Đa khoa Phú Yên thành lập khoa Ung bướu',
 'Cách quan hệ không mang thai và cách tránh thai an toàn từ bác sĩ',
 '10 lợi ích sức khỏe của thảo quả | Sức khỏe Việt',
 'Bất ngờ công dụng làm đẹp từ bia',
 '10 thói quen nên duy trì thực hiện để có tuổi già khỏe mạnh, hạnh phúc',
 '13 học sinh Trường cao đẳng Công nghiệp Thái Nguyên sắp ra viện',
 'Thầy thuốc Nhân dân Nguyễn Quốc Hùng: Hành trình 35 năm vì sức khỏe cộng đồng',
 '12 tuổi nhưng nặng 83kg, bé trai suy hô hấp nặng, tổn thương gan khi mắc sốt xuất huyết',
 '1.305 trẻ được tiêm vắc xin sởi trong chiến dịch tiêm đợt 3',
 '27 công nhân nhập viện nghi ngộ độc thực phẩm sau bữa cơm trưa tại công ty',
 '10 nguyên tắc vàng trong ăn uống',
 '42 tỉnh, thành phố đã công bố loại trừ bệnh sốt rét',
 '15 tuổi đã bị "máu vàng, gan vàng" vì nghiện ăn trứng',
 '4 ca tử vong do cúm tại Bình Định đều có nhiều bệnh nền - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '12 cách chữa viêm da cơ địa tại nhà hiệu quả, an toàn, tiết kiệm',
 'Phụ nữ Bệnh viện Bỏng Quốc gia Lê Hữu Trác: Đoàn kết Trí tuệ',
 '4 bài tập tại nhà giúp giữ cơ, dáng đẹp sau tết',
 '4 người nhập viện do rò rỉ khí làm lạnh tại một cơ sở sản xuất nước đá',
 '12 loại trái cây sấy khô tốt nhất',
 'Phê duyệt bốn tài liệu về phòng, chống dịch Covid-19 trong trường học',
 'Bảo đảm công tác khám, chữa bệnh và không để dịch bệnh bùng phát sau mưa bão',
 '10 câu hỏi thường gặp về viêm gan B',
 '7 ứng xử sai lầm của cha mẹ khiến trẻ không thành công | Bệnh viện Nhi Trung ương',
 '10 bài tập chân cơ bản giúp trái tim khỏe mạnh hơn',
 'Có nên dùng tinh dầu ngải trị liệu đau xương khớp không?',
 '1 trẻ chết, 3 trẻ khác ốm vì nhiễm khuẩn sau khi chơi với vật nuôi',
 'Giải pháp làm sạch dịu nhẹ, giúp làn da khô đến thiếu ẩm luôn dễ chịu sau mỗi lần rửa mặt',
 'An toàn thực phẩm: Giải pháp cho nhà quản lý và người tiêu dùng Bài cuối: Cộng đồng trách nhiệm trong bảo vệ sức khỏe người tiêu dùng',
 '4 loại thực phẩm giúp bạn tăng cường khả năng tập trung • Hello Bacsi',
 '2 cách đơn giản phòng thoát vị đĩa đệm',
 '10 tư thế yoga tốt nhất cho nam giới',
 '10 công dụng bất ngờ của trà hạt thì là',
 '1 loại quả có tác dụng ức chế tế bào ung thư, ngừa bệnh tiểu đường mà người Nhật ăn nhiều',
 '10 dấu hiệu sốt xuất huyết nặng cần nhận biết để cấp cứu kịp thời - Trung tâm Tiêm chủng Long Châu',
 'Các đối tượng dễ bị đột quỵ',
 '1.926 người kinh doanh, giết mổ chó, mèo thịt âm tính với SARS-CoV-2',
 '10 bước đơn giản giúp loại bỏ độc tố khỏi phổi',
 '10 dấu hiệu của bệnh thoát vị đĩa đệm',
 '“Bệnh khó nói” mà dễ trị của chị em',
 'Tại sao mùa hè dễ bị ngộ độc thực phẩm?',
 '10 bài thuốc trị bệnh từ lá trà xanh, dùng đúng để mang lại lợi ích cho sức khoẻ',
 'Bệnh thận đái tháo đường: Những lời khuyên hữu ích từ chuyên gia - Bệnh viện Việt Đức',
 '23 loại thực phẩm tăng cường sinh lý cho nam giới - YouMed News',
 '1 trường hợp dương tính liên quan đến BN 1440',
 '10 thực phẩm và đồ uống giúp “giải cứu” đường ruột khi bị táo bón',
 'Bí quyết để các quý ông thực sự là phái mạnh',
 '143 người tử vong do bệnh lạ ở CHDC Congo',
 '5 trường hợp nhân viên y tế có quyền từ chối khám, chữa bệnh',
 '10 thực phẩm cung cấp canxi tự nhiên cho cơ thể | Sức khỏe Việt',
 '3 trẻ ở Đà Nẵng nhập viện cấp cứu sau khi ăn cá ủ chua',
 '153 nhân viên y tế Gia Lai tham dự tập huấn chăm sóc sức khỏe người cao tuổi',
 'Bệnh viện Quân y 211: Đột phá nâng chất lượng khám, chữa bệnh',
 '5 bệnh mùa nắng nóng trẻ dễ mắc - Báo và Phát thanh, Truyền hình Lạng Sơn',
 '13 Cách trị mụn tại nhà từ thiên nhiên hiệu quả chỉ sau 1 tuần thực hiện',
 '4 tiếng phẫu thuật cắt khối u trực tràng, u gan, ruột non cho bệnh nhân 76 tuổi',
 '13 trung tâm y tế khu vực tại TP.HCM sẽ được chuyển đổi thành bệnh viện',
 '50 công nhân nhập viện sau bữa ăn trưa tại một công ty ở TPHCM',
 '14 lợi ích sức khỏe khi uống trà chanh',
 'Bảo hiểm Xã hội thông tin về việc bảo hiểm y tế ngừng chi trả ca bệnh nặng',
 '10 sự kiện nổi bật của ngành y tế TP.HCM - năm 2025',
 '4 nhóm người cần hạn chế uống cà phê sữa dù thích đến mấy',
 'Bố trí kíp trực y tế tại các điểm thi tốt nghiệp trung học phổ thông',
 'Hội chứng Down có di truyền không?',
 'Bắc Ninh: Vingroup hỗ trợ xây dựng hệ thống cấp cứu ngoại viện chuẩn quốc tế - mỗi cuộc gọi 115 là một cơ hội sống',
 '1 triệu du khách Hàn Quốc và lời cảm ơn từ Đà Nẵng: Tuần lễ tri ân khởi động chuỗi kích cầu du lịch quốc tế | Sức Khỏe Cộng Đồng',
 '13 người nhập viện sau khi ăn trứng cá rồng',
 '10 bài tập giúp cải thiện tư thế cho người ngồi nhiều',
 '10 dấu hiệu nhận biết nguy hiểm cho sức khoẻ',
 'Điều trị bệnh sốt rét tại nhà nguy hiểm không? Làm cách nào để sớm khỏi bệnh?',
 '1 trường hợp tử vong nghi do bệnh tay chân miệng',
 'Đâu là cách bảo quản rau trong tủ lạnh hiệu quả nhất? • Hello Bacsi',

In [94]:
def display_chunks(doc_id: int, text: str):
    chunks = chunker.chunk_document(doc_id=str(doc_id), text=text, lang="vi")
    # 4. Xem kết quả
    print(f"Tổng số chunks tạo ra: {len(chunks)}\n")
    for i, c in enumerate(chunks):
        print(f"🔹 [Chunk {i+1}] ID: {c.chunk_id} | Vị trí: [{c.char_start}:{c.char_end}] | Độ dài: {len(c.chunk_text)} ký tự")
        print(f"\"{c.chunk_text}\"\n")

In [108]:
display_chunks("1", vi_sentences[1000]["text"])

Tổng số chunks tạo ra: 4

🔹 [Chunk 1] ID: 1__c0 | Vị trí: [0:1200] | Độ dài: 1199 ký tự
"5 điều cần biết để ăn hải sản không bị ngộ độc
Khi đi biển nghỉ mát và thưởng thức hải sản, ăn thế nào cũng là vấn đề quan trọng, Trung tâm chống độc Bệnh viện Bạch Mai có hướng dẫn như sau:
1. Chỉ ăn loại hải sản được biết chắc chắn không có chất độc:
- Đây chính là các loại hải sản chúng ta vẫn thường ăn. Điều này không phải vì yếu tố “tâm lý đám đông”, các hải sản đó rõ ràng an toàn.
- Thận trọng khi ăn các loại hải sản lạ, ít khi được ăn. Đây thực sự là sở thích khám phá của nhiều người. Tuy nhiên, cần cân nhắc trước khi ăn thử. Lý do các loại hải sản này ít được ăn cũng có thể từng được biết là có thể gây ngộ độc, hoặckhông ai biết có gây ngộ độc hay không. Vì vậy đây cũng là nhóm hải sản có thể gây ngộ độc và nên tránh.
2. Biết và tránh các loại hải sản được biết có thể chứa chất độc:
Có loại hải sản luôn luôn có chất độc, có loại thường có hoặc thỉnh thoảng mới có. Tuy nhiên, bằng mắt thường và cảm giác khi ăn uống chúng ta không thể phát hiện có chất độc hay không, vì vậy với các loại hải sản này bạn cần biết và tránh ăn. Các loại hải sản có độc như: cá nóc, bạch tuộc vòng xanh, sam biển, sao biển… Có thể tham khảo các nguồn thông tin khác và hỏi thêm người dân địa phương."

🔹 [Chunk 2] ID: 1__c1 | Vị trí: [1046:2238] | Độ dài: 1191 ký tự
"Các loại hải sản có độc như: cá nóc, bạch tuộc vòng xanh, sam biển, sao biển… Có thể tham khảo các nguồn thông tin khác và hỏi thêm người dân địa phương. Các loại độc tố này thường không bị phá hủy bởi nhiệt nóng khi đun nấu và các biện pháp chế biến thông thường.
3. Chỉ nên ăn thức ăn được chế biến từ hải sản tươi sống, không nên ăn các thức ăn đã chế biến từ lâu:
Hải sản nói chung là các loại thực phẩm nguồn gốc từ động vật, rất giàu chất đạm (protein), khi bị chết hoặc bảo quản ở nhiệt độ thông thường rất nhanh chóng bị các vi khuẩn xâm nhập và phát triển nên dễ gây bệnh. Với một số loại hải sản như cá ngừ, cá thu, vi khuẩn thậm chí biến thịt của cá thành chất độc (chuyển một loại acid amin là histidin trong thịt cá thành chất độc histamin) gây ngộ độc (đỏ da, nóng bừng, trống ngực, đau đầu, khó thở…). Nếu chỉ ăn thức ăn được chế biến hợp vệ sinh từ hải sản còn tươi sống, sau chế biến ăn ngay, không có khâu nào trong giai đoạn từ lúc chế biến đến bàn ăn bị ô nhiễm thì chắc chắn sẽ không bị ngộ độc hải sản do các loại vi trùng. Các hải sản đông lạnh có thể an toàn về mặt vi khuẩn nếu được bảo quản đông lạnh liên tục từ khi còn sống tới khi mua và chưa quá hạn sử dụng.
4."

🔹 [Chunk 3] ID: 1__c2 | Vị trí: [2092:3282] | Độ dài: 1189 ký tự
"Các hải sản đông lạnh có thể an toàn về mặt vi khuẩn nếu được bảo quản đông lạnh liên tục từ khi còn sống tới khi mua và chưa quá hạn sử dụng.
4. Để ý tới các thông tin về nhiễm độc nước biển, ô nhiễm môi trường ở vùng biển bạn sẽ tới:
Bên cạnh các vấn đề ô nhiễm môi trường do hóa chất bạn có thể biết rõ, có một hiện tượng tự nhiên đặc biệt xảy ra chỉ riêng với biển có thể dẫn tới ngộ độc là hiện tượng “thủy triều đỏ”. “Thủy triều đỏ” là hiện tượng nước biển đổi màu bất thường như hồng, tía, xanh lục, nâu hay đỏ. Nguyên nhân do một số loại tảo biển phát triển ồ ạt với số lượng lớn bất thường. Một số loại tảo có chứa chất độc. Các hải sản lúc bình thường có thể không có độc nhưng khi có thủy triều đỏ có thể mang tảo độc và gây ngộ độc. Không nên ăn các hải sản được đánh bắt ở vùng có “thủy triều đỏ”, đặc biệt các loài động vật thân mềm có hai mảnh vỏ (như trai, sò, ngao…).
5. Chỉ nên ăn các hải sản được nấu chín:
- Các vi khuẩn rất dễ phát triển trong hải sản. Có thể có một số phương pháp chế biến thực phẩm không bằng nhiệt nóng (như đun, nấu) nhưng vẫn có thể đủ tiêu diệt các vi trùng để cho phép ăn tươi. Tuy nhiên, với chế biến thủ công thì nhất thiết phải bằng đun nấu."

🔹 [Chunk 4] ID: 1__c3 | Vị trí: [3215:3860] | Độ dài: 645 ký tự
"Tuy nhiên, với chế biến thủ công thì nhất thiết phải bằng đun nấu.
Điều cuối cùng các bạn nên biết các biểu hiện của ngộ độc do ăn hải sản như thế nào để có thể phát hiện nhanh. Nói chung có nhiều loại hải sản với nhiều loại nguyên nhân gây độc khác nhau nên biểu hiện ngộ độc hải sản cũng rất đa dạng: từ đau bụng, nôn, tiêu chảy, sốt đến các biểu hiện thần kinh như tê môi lưỡi, co giật, liệt, mờ mắt, lẫn lộn, hôn mê; hay tim mạch như loạn nhịp tim, tụt huyết áp; hay hô hấp như khó thở, thậm chí tử vong. Nói chung các ngộ độc sẽ nguy hiểm nếu bạn có các biểu hiện thần kinh, tim mạch, hô hấp hoặc khi các biểu hiện ngộ độc kéo dài không đỡ."

In [111]:
corpus_urls = []
for index, row in corpus.iterrows():
    corpus_urls = row['url']

In [112]:
set(corpus_urls)

{'.',
 '/',
 ':',
 'a',
 'b',
 'c',
 'e',
 'h',
 'i',
 'j',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'y',
 'z'}